### ISSUE TITLE
Amazon AWS one click launch button in README.md is out of date

### ISSUE THREAD

**Issue by reedhedges** [mxpv/podsync#101]
Or rather `https://podsync-cf.s3.amazonaws.com/cloud_formation.yml` is out of date -- it does not have the hostname parameter fix.    [Or use `https://raw.githubusercontent.com/mxpv/podsync/master/cloud_formation.yml` as the URL instead of the S3 URL?]

(In the mean time, users can download he current version of `cloud_formation.yml` from the repository, use the button to start setting up the CloudFormation stack config, but Update the template with the newer version.)

**Comment by mxpv** [comment]
Sorry for delay. I've uploaded new CF template.
