### ISSUE TITLE
clean function doesn't work

### ISSUE THREAD

**Issue by ahmedahmedo** [mxpv/podsync#102]
clean function doesn't work or I don't know how to write accurately script.
which one is correct notation?

`  # clean = { keep_last = 10 } # Keep last 10 episodes (order desc by PubDate)
`

clean = 10 
clean = { keep_last = 10 } 
keep_last = 10

**Comment by mxpv** [comment]
Unit tests seems to be passing for the configuration:
https://github.com/mxpv/podsync/blob/5997a392b1e8c8075917a8452fcee8ceb87fd102/pkg/config/config_test.go#L36

Can you elaborate what exactly is not working?

**Comment by ahmedahmedo** [comment]
I can download YouTube videos `"/app/data"`
when I run Podsync by docker it download new videos but doesn't delete old files.

my config file's code is like this
`clean = { keep_last = 10 }`

**Comment by SoftXperience** [comment]
Maybe it's the same problem like with max_height. It seems that these changes are merged on the  master branch, but the last release (so also the last docker version) is from 27. Jan. So I guess it is not yet included. Would be great to get a new release soon!

**Comment by mxpv** [comment]
Right. Master branch wasn't released yet, it needs some testing.

**Comment by mxpv** [comment]
Try latest release: https://github.com/mxpv/podsync/releases/tag/v2.1.0
