### ISSUE TITLE
Got Too Many Requests Error

### ISSUE THREAD

**Issue by Rumik** [mxpv/podsync#109]
Hey there,

lately I've been seeing this a lot: "got too many requests error, will retry download next time" episode_id=LXCAVKQmfz0 error="failed to execute youtube-dl: exit status 1"

I've tried changing my API but it didn't make any difference.

Any advice? Thanks.

**Comment by mxpv** [comment]
That means that you're sending too many download requests and YouTube bans your IP address. You'd need to reduce downloads frequency.

**Comment by Rumik** [comment]
What exactly does that mean - reduce how often I look for new episodes and/or reduce the page size?

Thanks!

**Comment by mxpv** [comment]
> reduce how often I look for new episodes 

this one.

**Comment by Rumik** [comment]
Okay thank you :)

**Comment by pseigo** [comment]
@mxpv If requesting new episodes too often is produced by the client, maybe the server can cache YouTube API calls with a configurable lifetime to prevent this from happening (if something like this isn't being done already)?

**Comment by mxpv** [comment]
@pseigo we do cache all info between calls, that's how Podsync generates feeds.
But it's up to user how often to check for updates. For instance, you can host 100 channels and check them once a month, or you can have 1 channel and check updates every hour. I don't think we require some extra logic here.
