### ISSUE TITLE
Trouble Starting PodSync after Upgrade

### ISSUE THREAD

**Issue by Rumik** [mxpv/podsync#115]
Hi there,

I'm having trouble starting the new version of podsync after creating a new container with the latest docker image... "error="failed to load config file: toml: cannot load TOML value of type string i                   nto a Go integer"

Any ideas?

Thanks

**Comment by online-ua** [comment]
max_height = 720

without quotes

**Comment by Rumik** [comment]
Oh it's not supposed to have quotes? Weird... the example config includes them.

**Comment by jtagcat** [comment]
Next time make a PR..
