### ISSUE TITLE
Value log truncate required to run DB error

### ISSUE THREAD

**Issue by richardwarriner** [mxpv/podsync#116]
Running 2.1.0 
Added to config to keep last 10 and ran through ok. If i close the window and then reload it fails to start with below message. Deleting the db folder makes it work ok again but only until window si closed again. 
Also in the db folder is 000000.vlog which is just over 2gb
Is it me?

libavutil      56. 35.101 / 56. 35.101
libavcodec     58. 62.100 / 58. 62.100
libavformat    58. 35.100 / 58. 35.100
libavdevice    58.  9.100 / 58.  9.100
libavfilter     7. 66.100 /  7. 66.100
libswscale      5.  6.100 /  5.  6.100
libswresample   3.  6.100 /  3.  6.100
 ibpostproc    55.  6.100 / 55.  6.100
INFO[2020-04-14T08:02:25+01:00] opening database "db"
INFO[0001] All 0 tables opened in 0s
INFO[0001] Replaying file id: 0 at offset: 0
FATA[2020-04-14T08:02:25+01:00] failed to open database                       error="failed to open database: Value log truncate required to run DB. This might result in data loss"

**Comment by mxpv** [comment]
When you close a window, does it have time to shutdown properly?

**Comment by richardwarriner** [comment]
I have a .bat file on windows which contains just podsync.exe --config config.txt

The running window is just CMD.exe so i am just clicking the X in the top right corner

**Comment by mxpv** [comment]
Can you try "Ctrl+C" instead? You should see `gracefully stopped` message at the very end if it shutdowns properly.

**Comment by richardwarriner** [comment]
I do indeed and then a terminate batch job. Answering Y to this gets me fully out and the app does then restart without error.
Its a bit easy to do by accident though and not sure what will happen if the machine reboots for updates?

**Comment by mxpv** [comment]
Ok, I found a few similar issues: https://github.com/dgraph-io/badger/issues/744 https://github.com/jaegertracing/jaeger/issues/1832 that suggest to enable `Truncate` option. I'm going to rollout `2.1.1` with the quick fix.

**Comment by richardwarriner** [comment]
Thanks

**Comment by mxpv** [comment]
@richardwarriner did it help?

**Comment by richardwarriner** [comment]
Its would seem so. I can force close the window and it goes back in ok. I also just had the box reboot with windows updates and it was ok when i went back in
