### ISSUE TITLE
Help building Cron schedules

### ISSUE THREAD

**Issue by Rumik** [mxpv/podsync#117]
Hi there,

PodSync seems to only support 5 field cron schedules... so how do you incorporate specific days of the week? I'm trying to use this: "0 0 05 ? * TUE-SAT", the intention being to check for new episodes at 5 am Tue-Sat, but if PodSync only supports 5 fields how do I do that?

Thanks.

**Comment by Rumik** [comment]
Ah no worries, I removed the first and last fields :P

**Comment by richardwarriner** [comment]
Could you post the exact string you used? I had the same issue and gave up !

**Comment by Rumik** [comment]
Sure... here's one for 5 am Tue-Sat: cron_schedule = "0 5 ? * TUE-SAT"
And one for just Thursday: cron_schedule = "0 05 * * THU"

**Comment by tapatianbeast** [comment]
> Sure... here's one for 5 am Tue-Sat: cron_schedule = "0 5 ? * TUE-SAT"
> 
> And one for just Thursday: cron_schedule = "0 05 * * THU"

If i want 9am & 17pm everyday?

**Comment by Rumik** [comment]
0 9,17 ? * * I think!

**Comment by tapatianbeast** [comment]
> 0 9,17 ? * * I think!

But why his question Mark? On Linux will be 0 9,17 * * *

**Comment by Rumik** [comment]
Honestly I’ve no idea mate, if it works it works!

**Comment by tapatianbeast** [comment]
> Honestly I’ve no idea mate, if it works it works!

Sir hi again do you know where is database?
