### ISSUE TITLE
Failed to open database: Map log file - release 2.1

### ISSUE THREAD

**Issue by Fullmono** [mxpv/podsync#118]
Hi, 
I just give a try to last release but I have an error. 

Here is podsync output: 
`INFO[2020-04-14T10:56:46+02:00] running podsync                               commit=ac8a889ddb9e62393b5210771360bd320f1820e6 date="2020-04-14T00:34:52Z" version=2.1.0
INFO[2020-04-14T10:56:47+02:00] using youtube-dl 2019.11.28
INFO[2020-04-14T10:56:48+02:00] using ffmpeg ffmpeg version 3.2.12-1~deb9u1+rpt1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 34.101 / 55. 34.101
libavcodec     57. 64.101 / 57. 64.101
libavformat    57. 56.101 / 57. 56.101
libavdevice    57.  1.100 / 57.  1.100
libavfilter     6. 65.100 /  6. 65.100
libavresample   3.  1.  0 /  3.  1.  0
libswscale      4.  2.100 /  4.  2.100
libswresample   2.  3.100 /  2.  3.100
libpostproc    54.  1.100 / 54.  1.100
INFO[2020-04-14T10:56:48+02:00] opening database "Podsync/db"
INFO[0001] All 0 tables opened in 0s
INFO[0002] Replaying file id: 0 at offset: 0
INFO[0002] Replay took: 65.052µs
FATA[2020-04-14T10:56:48+02:00] failed to open database                       error="failed to open database: Map log file. Path=Podsync/db/000000.vlog. Error=cannot allocate memory"
`
vlog file is empty

I'm running on a raspberry pi 3.0 (armv6 architecture)

Regards,

**Comment by mxpv** [comment]
Is it a fresh start ?

**Comment by Fullmono** [comment]
Yes, I just retried with release 2.1.1 but I still have this error.

**Comment by mxpv** [comment]
How much free memory do you have?

**Comment by Fullmono** [comment]
Several gigs...

**Comment by mxpv** [comment]
Can you try `v2.2.0` and add the following configuration:
```toml

[database]
  badger = { truncate = true, file_io = true }
```

**Comment by Fullmono** [comment]
It's working, thank you for your great work!

**Comment by mxpv** [comment]
Thanks for the update.
