### ISSUE TITLE
Key not found error

### ISSUE THREAD

**Issue by richardwarriner** [mxpv/podsync#120]
I just installed 2.2 and did a full refresh. Deleted the db and my download folder first.

Getting a key not found error after each feed has downloaded. Everything seems ok though as the xml has been created. Maybe due to it being the first time?

INFO[2020-04-16T07:32:14+01:00] successfully downloaded file "kfcGbWKJIR0"    episode_id=kfcGbWKJIR0 index=3
INFO[2020-04-16T07:32:14+01:00] ! downloading episode https://youtube.com/watch?v=xQDmX38hos4  episode_id=xQDmX38hos4 index=4
INFO[2020-04-16T07:32:24+01:00] successfully downloaded file "xQDmX38hos4"    episode_id=xQDmX38hos4 index=4
INFO[2020-04-16T07:32:24+01:00] downloaded 4 episode(s)
ERRO[2020-04-16T07:32:24+01:00] failed to update feed: https://www.youtube.com/user/filmriot/videos  error="Key not found"
INFO[2020-04-16T07:32:24+01:00] -> updating https://www.youtube.com/user/vat19com/videos  feed_id=VAT19 format=video quality=high
INFO[2020-04-16T07:32:24+01:00] download count: 5
INFO[2020-04-16T07:32:24+01:00] ! downloading episode https://youtube.com/watch?v=97OfRNNFqJo  episode_id=97OfRNNFqJo index=0
INFO[2020-04-16T07:32:51+01:00] successfully downloaded file "97OfRNNFqJo"    episode_id=97OfRNNFqJo index=0
INFO[2020-04-16T07:32:51+01:00] ! downloading episode https://youtube.com/watch?v=T-N1JE0lK2I  episode_id=T-N1JE0lK2I index=1
INFO[2020-04-16T07:33:14+01:00] successfully downloaded file "T-N1JE0lK2I"    episode_id=T-N1JE0lK2I index=1
INFO[2020-04-16T07:33:14+01:00] ! downloading episode https://youtube.com/watch?v=bVFCTDBUpn8  episode_id=bVFCTDBUpn8 index=2
INFO[2020-04-16T07:33:31+01:00] successfully downloaded file "bVFCTDBUpn8"    episode_id=bVFCTDBUpn8 index=2
INFO[2020-04-16T07:33:31+01:00] ! downloading episode https://youtube.com/watch?v=e_9lMAmeoz4  episode_id=e_9lMAmeoz4 index=3
INFO[2020-04-16T07:34:08+01:00] successfully downloaded file "e_9lMAmeoz4"    episode_id=e_9lMAmeoz4 index=3
INFO[2020-04-16T07:34:08+01:00] ! downloading episode https://youtube.com/watch?v=xZgPWhHXKd0  episode_id=xZgPWhHXKd0 index=4
INFO[2020-04-16T07:34:31+01:00] successfully downloaded file "xZgPWhHXKd0"    episode_id=xZgPWhHXKd0 index=4
INFO[2020-04-16T07:34:31+01:00] downloaded 5 episode(s)
ERRO[2020-04-16T07:34:32+01:00] failed to update feed: https://www.youtube.com/user/vat19com/videos  error="Key not found"
INFO[2020-04-16T07:34:32+01:00] -> updating https://www.youtube.com/user/testedcom/videos  feed_id=Tested format=video quality=high

**Comment by tuxpeople** [comment]
No. It's also happening when you do another run:

`INFO[2020-04-16T09:15:08Z] -> updating https://www.youtube.com/channel/UCdsHMu1VHhZ8SlrdUQa457w  feed_id=spotfightnews format=audio quality=high
INFO[2020-04-16T09:15:08Z] download count: 5
INFO[2020-04-16T09:15:08Z] episode "UIUntgi3sXg" already exists on disk  episode_id=UIUntgi3sXg index=0
INFO[2020-04-16T09:15:08Z] episode "YdD7auyuO3g" already exists on disk  episode_id=YdD7auyuO3g index=1
INFO[2020-04-16T09:15:08Z] episode "ZUcex-_HCgY" already exists on disk  episode_id=ZUcex-_HCgY index=2
INFO[2020-04-16T09:15:08Z] episode "b4-KtYMafyA" already exists on disk  episode_id=b4-KtYMafyA index=3
INFO[2020-04-16T09:15:08Z] episode "tqHE67IAYmw" already exists on disk  episode_id=tqHE67IAYmw index=4
INFO[2020-04-16T09:15:08Z] downloaded 0 episode(s)
ERRO[2020-04-16T09:15:08Z] failed to update feed: https://www.youtube.com/channel/UCdsHMu1VHhZ8SlrdUQa457w  error="Key not found"`

**Comment by tapatianbeast** [comment]
> I just installed 2.2 and did a full refresh. Deleted the db and my download folder first.
> 
> Getting a key not found error after each feed has downloaded. Everything seems ok though as the xml has been created. Maybe due to it being the first time?
> 
> INFO[2020-04-16T07:32:14+01:00] successfully downloaded file "kfcGbWKJIR0" episode_id=kfcGbWKJIR0 index=3
> INFO[2020-04-16T07:32:14+01:00] ! downloading episode https://youtube.com/watch?v=xQDmX38hos4 episode_id=xQDmX38hos4 index=4
> INFO[2020-04-16T07:32:24+01:00] successfully downloaded file "xQDmX38hos4" episode_id=xQDmX38hos4 index=4
> INFO[2020-04-16T07:32:24+01:00] downloaded 4 episode(s)
> ERRO[2020-04-16T07:32:24+01:00] failed to update feed: https://www.youtube.com/user/filmriot/videos error="Key not found"
> INFO[2020-04-16T07:32:24+01:00] -> updating https://www.youtube.com/user/vat19com/videos feed_id=VAT19 format=video quality=high
> INFO[2020-04-16T07:32:24+01:00] download count: 5
> INFO[2020-04-16T07:32:24+01:00] ! downloading episode https://youtube.com/watch?v=97OfRNNFqJo episode_id=97OfRNNFqJo index=0
> INFO[2020-04-16T07:32:51+01:00] successfully downloaded file "97OfRNNFqJo" episode_id=97OfRNNFqJo index=0
> INFO[2020-04-16T07:32:51+01:00] ! downloading episode https://youtube.com/watch?v=T-N1JE0lK2I episode_id=T-N1JE0lK2I index=1
> INFO[2020-04-16T07:33:14+01:00] successfully downloaded file "T-N1JE0lK2I" episode_id=T-N1JE0lK2I index=1
> INFO[2020-04-16T07:33:14+01:00] ! downloading episode https://youtube.com/watch?v=bVFCTDBUpn8 episode_id=bVFCTDBUpn8 index=2
> INFO[2020-04-16T07:33:31+01:00] successfully downloaded file "bVFCTDBUpn8" episode_id=bVFCTDBUpn8 index=2
> INFO[2020-04-16T07:33:31+01:00] ! downloading episode https://youtube.com/watch?v=e_9lMAmeoz4 episode_id=e_9lMAmeoz4 index=3
> INFO[2020-04-16T07:34:08+01:00] successfully downloaded file "e_9lMAmeoz4" episode_id=e_9lMAmeoz4 index=3
> INFO[2020-04-16T07:34:08+01:00] ! downloading episode https://youtube.com/watch?v=xZgPWhHXKd0 episode_id=xZgPWhHXKd0 index=4
> INFO[2020-04-16T07:34:31+01:00] successfully downloaded file "xZgPWhHXKd0" episode_id=xZgPWhHXKd0 index=4
> INFO[2020-04-16T07:34:31+01:00] downloaded 5 episode(s)
> ERRO[2020-04-16T07:34:32+01:00] failed to update feed: https://www.youtube.com/user/vat19com/videos error="Key not found"
> INFO[2020-04-16T07:34:32+01:00] -> updating https://www.youtube.com/user/testedcom/videos feed_id=Tested format=video quality=high

Where is the database?

**Comment by mxpv** [comment]
Can you provide an example of configuration you use?

**Comment by richardwarriner** [comment]
[config.txt](https://github.com/mxpv/podsync/files/4489713/config.txt)

Here you go. Removed my url

**Comment by mxpv** [comment]
@richardwarriner you'd need to re-generate your YT API token 😢

**Comment by richardwarriner** [comment]
Rookie error - done

**Comment by richardwarriner** [comment]
i just closed and reran with the new key and its not showing the error now. It seems to be just the first time i ran after deleting db and data folders and restarting.

**Comment by mxpv** [comment]
I finally figured it out. Can you please try v2.2.1 ?

**Comment by richardwarriner** [comment]
I seems to be working but to be 100% sure i will need to wipe my data folder and download all again which is 60+gb 
Might try it over the weekend

**Comment by mxpv** [comment]
There is no need to re-download everything, just check logs during update process. There should be no “Key not found” error.

**Comment by richardwarriner** [comment]
In that case all seems fine. It ran through, no errors and new files were downloaded :)
Thanks for your work on this - its invaluable!

**Comment by tuxpeople** [comment]
Can confirm with a redploy of "latest" (2.2.1), the error is not showing up! thanks a lot!
