### ISSUE TITLE
getting lots of youtube dl errors

### ISSUE THREAD

**Issue by Rumik** [mxpv/podsync#127]
Hi there,

I'm getting lots of youtube dl errors, can you tell me what they mean please?:

time="2020-04-18T10:40:03Z" level=error msg="[youtube] KVeuxxWHmhk: Downloading webpage\n[youtube] KVeuxxWHmhk: Downloading video info webpage\nERROR: Signature extraction failed: Traceback (most recent call last):\n  File \"/usr/bin/youtube-dl/youtube_dl/e
xtractor/youtube.py\", line 1385, in _decrypt_signature\n    video_id, player_url, s\n  File \"/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py\", line 1262, in _extract_signature_function\n    raise ExtractorError('Cannot identify player %r' % player_ur
l)\nExtractorError: Cannot identify player u'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure 
to call youtube-dl with the --verbose flag and include its complete output.\n (caused by ExtractorError(u\"Cannot identify player u'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n"     

thanks

**Comment by mxpv** [comment]
youtube-dl needs update. try `youtube-dl --update --verbose`.
This also will be addressed in https://github.com/mxpv/podsync/issues/119

**Comment by Rumik** [comment]
Ah great, thank you!
