### ISSUE TITLE
Episode Unavailable

### ISSUE THREAD

**Issue by john-catalano** [mxpv/podsync#143]
http://10.0.0.2:8081/ID1.xml

This URL, above, will serve the podcast files to my local machine on which Podsync in Docker is installed. And, my iOS devices will see that URL and subscribe the the podcast. However, while my Mac will play the files, my iOS devices will not.

I get a message in iOS that says "Episode Unavailable". 

Is there another setting to allow clients to actually get the media from the URL, above?

To be sure, I can, in the iOS Files.app, browse into the folders that contain the xml and podcast files. I can even play the files via the Files.app. But, I want to be able to do this in the iOS Podcast.app.

**Comment by 726a67** [comment]
I'm pretty sure Apple [requires](https://help.apple.com/itc/podcasts_connect/#/itc1723472cb) podcast feeds to resolve to publicly addressable servers -- your current feed structure points to a private address.

If your Mac is on the same private network as your Podsync server, it probably won't have any issue locally resolving/playing the content (depending on the playback method). Likewise with the Files app on your iOS devices.

However, most podcast clients have external checks/dependencies that can't be met with a privately-served feed.

**Comment by john-catalano** [comment]
I wouldn't have guessed that. Thank you.

**Comment by chudeyang0225** [comment]
Any clear solution to this? I'm having the same issue.
