### ISSUE TITLE
Unable to download video (outdated youtube-dl in docker-compose?)

### ISSUE THREAD

**Issue by Arkkimaagi** [mxpv/podsync#160]
So I was unable to get the latest video even tho podsync has worked with docker-compose just fine up until now. (well, okay, paging has not worked)

I checked the log and sure enough, found this:

> time="2020-07-21T14:39:17Z" level=info msg="downloading episodes" page_size=50
> 
> time="2020-07-21T14:39:17Z" level=info msg="download count: 1"
> cker-com
> time="2020-07-21T14:39:17Z" level=info msg="! downloading episode https://youtube.com/watch?v=hKlo5FWlxnA" episode_id=hKlo5FWlxnA index=0
> 
> time="2020-07-21T14:39:21Z" level=error msg="youtube-dl error: /tmp/podsync-546637666/hKlo5FWlxnA.%(ext)s" error="failed to execute youtube-dl: exit status 1"
> 
> time="2020-07-21T14:39:21Z" level=error msg="[youtube] hKlo5FWlxnA: Downloading webpage\n[youtube] hKlo5FWlxnA: Downloading video info webpage\nERROR: hKlo5FWlxnA: \"token\" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n"
> 
> time="2020-07-21T14:39:21Z" level=info msg="downloaded 0 episode(s)"
> 

I checked the logs for the version, which seems to be old.
> using youtube-dl 2020.01.24

I did not have youtube-dl installed in my system as it all has been contained in docker.

I tried installing an up to date version of youtube-dl, but of course it still finds the old version inside docker.

In my system:
> $ youtube-dl --version
> 2018.03.14

But docker log:
> using youtube-dl 2020.01.24

Then I tried the trick mentioned in https://github.com/mxpv/podsync/issues/119#issuecomment-624031834 but the docker-compose will not run, but complain instead

> unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

And yep, it's creating a folder named youtube-dl instead of linking a binary or what ever it's supposed to do.

**How can I update the youtube-dl version the docker-compose is using?**

**Comment by Arkkimaagi** [comment]
I also tried getting even more recent version of youtube-dl straight from repo, but I do not know how to link it to docker-compose.

**Comment by Arkkimaagi** [comment]
I was able to bypass this by running "youtube-dl -U" from portainer.

**Comment by Rpsl** [comment]
see https://github.com/mxpv/podsync/issues/119

**Comment by ctrl-b** [comment]
I was able to work around this by mounting the binary, I use podman though

**Comment by mxpv** [comment]
Have you tried this?

```toml
[downloader]
self_update = true # Optional, auto update youtube-dl every 24 hours
```

**Comment by Arkkimaagi** [comment]
I had not noticed that setting 😊  I'll try running with that.

**Comment by 726a67** [comment]
@Arkkimaagi note that the current youtube-dl release has an [open issue](https://github.com/ytdl-org/youtube-dl/issues/26152) affecting the download/extraction of certain youtube videos (particularly those restricted by age). Even if podsync grabs the latest version, you may continue to see errors. 

There is a patch you can apply manually to the youtube-dl executable, but you would need to disable podsync's youtube-dl self-update and explicitly mount the updated executable within your podsync container, at least until the patch is merged in the next release.
