### ISSUE TITLE
What to fill in for a category with subcategory?

### ISSUE THREAD

**Issue by hayschan** [mxpv/podsync#161]
According to Apple Podcast categories, [specify a category with a subcategory](https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12):

```
<itunes:category text="Society &amp; Culture">
  <itunes:category text="Documentary" />
</itunes:category>
```

For podsync, the corresponding line in the config file looks like this:
`custom = { cover_art = "{IMAGE_URL}}", category = "TV", explicit = true, lang = "en" } # Optional feed customizations`

What should I fill in for category if it is a Documentary under Society & Culture?

**Comment by mxpv** [comment]
Right now we specify top level category: https://github.com/mxpv/podsync/blob/master/pkg/feed/xml.go#L56
Should be easy to fix.
