### ISSUE TITLE
 msg="failed to load configuration file" error="failed to load config file: read config.toml: is a directory"

### ISSUE THREAD

**Issue by fishyo** [mxpv/podsync#164]
hello,i am not good at program and i made some wrong during the docker build and it prompt “ msg="failed to load configuration file" error="failed to load config file: read config.toml: is a directory"
so i have a few problems:

1.config.toml is a folder or file and where should i put it ？
2.if youtube-dl and ffmpeg is necessary when i run podsync with docker?
wait for your reply

my path is /root/podsync

The following is my docker-compose.yml content

`version: '2.2'

services:
  podsync:
    container_name: podsync
    image: mxpv/podsync:latest
    restart: always
    ports:
      - 9887:9887
    volumes:
      - ./data:/app/data/
      - ./config.toml:/app/config.toml`

**Comment by mxpv** [comment]
Try to use full path instead of `./data` and `./config.toml`
