### ISSUE TITLE
Feature Request - Is it possible to "Like" a video?

### ISSUE THREAD

**Issue by Rumik** [mxpv/podsync#166]
Hey there!

As always, love this app, couldn't live without it! But something has occured to me... I barely spend any time on YouTube anymore, so I never actually Like any of the videos I watch through PodSync... is there a way to set videos to liked for certain feeds? Seems unlikely but I figured I'd ask!

Thanks :)

**Comment by mxpv** [comment]
Unfortunately this is beyond the scope of this project. Particularly because I can't think of any way to integrate (variety of) existing podcast players with this kind of functionality. Also this would require to maintain a separate client on podsync side to call Youtube's API for adding likes.
