### ISSUE TITLE
Any way to reset a feed?

### ISSUE THREAD

**Issue by joejoe0243** [mxpv/podsync#170]
I am using docker image. I deleted a feed's folder and xml, but podsync would not re-create after restart.
Is there way to reset the feed?

**Comment by mxpv** [comment]
You'd need to delete database files as well

**Comment by joejoe0243** [comment]
> You'd need to delete database files as well

where is the database file located? Do I need to mount a path?

**Comment by mxpv** [comment]
Usually it's a path next to your config file (`db` directory)
