### ISSUE TITLE
youtube_dl_args not work

### ISSUE THREAD

**Issue by joejoe0243** [mxpv/podsync#174]
I want to download the latest episode in a playlist which that is sort by date ascending. 
I used youtube_dl_arg "--playlist-reverse" to download. It works with standalone youtube_dl but not work in podsync

sample playlist: https://www.youtube.com/playlist?list=PLVIxIjRNxFv5VRUXt66VzBxOys1GpmBp4

**Comment by ticky** [comment]
These arguments are only provided to youtube-dl when downloading individual videos. youtube-dl is not used to get playlist contents, just the videos themselves. You probably want to be tracking #84 instead.

**Comment by mxpv** [comment]
That's precisely correct. Please track #84
