### ISSUE TITLE
Youtube url format with youtube.com/c/CHANNEL doesn't work

### ISSUE THREAD

**Issue by pagdot** [mxpv/podsync#178]
Channel links like <https://www.youtube.com/c/AndreasKling> don't get recognised/error out:

```
time="2020-09-25T18:34:16Z" level=info msg="-> updating https://www.youtube.com/c/AndreasKling" feed_id=CarTalks2 format=audio quality=high
time="2020-09-25T18:34:16Z" level=error msg="failed to update feed: https://www.youtube.com/c/AndreasKling" error="update failed: failed to parse URL: https://www.youtube.com/c/AndreasKling: unsupported link format"
```
It works with the "real" channel link like <https://www.youtube.com/channel/UC3ts8coMP645hZw9JSD3pqQ> in this example.

**Comment by mxpv** [comment]
Any details ?

**Comment by pagdot** [comment]
I've added more details to the description :)

**Comment by mxpv** [comment]
Unfortunately there is no API which would let us to get a channel from user name (meaning that Youtube has no public API that would allow us to send `AndreasKling` and receive `UC3ts8coMP645hZw9JSD3pqQ`). Instead we can get https://www.youtube.com/user/andreaskling which is not what we want. 

API: https://developers.google.com/youtube/v3/docs/channels/list
