### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Dunuin** [mxpv/podsync#185]
Hi,

I installed the Podsync Docker Container running on a LXC container with docker running on a Proxmox Hypervisor.
The IP of the LXC Container is 192.168.42.68 and I configured all firewalls. I mapped the post 18080 on the host to port 8080 on the docker container and binded the config file and data dir.

If I try to access "http://192.168.42.68:18080/" or "http://192.168.42.68:18080/mobile/" I only get the Error: "403 Forbidden"

This is my config file:

```
[server]
port = 8080
data_dir = "/app/data" # Don't change if you run podsync via docker

# Tokens from `Access tokens` section
[tokens]
youtube = "MyAPIKey" # YouTube API Key. See https://developers.google.com/youtube/registering_an_application
#vimeo = [ # Multiple keys will be rotated.
  #"VIMEO_API_KEY_1", # Vimeo developer keys. See https://developer.vimeo.com/api/guides/start#generate-access-token
  #"VIMEO_API_KEY_2"
#]

[feeds]
  [feeds.mobile]
  url = "https://www.youtube.com/playlist?list=MyPlaylist" # URL address of a channel, group, user, or playlist.
  page_size = 50 # The number of episodes to query each update (keep in mind, that this might drain API token)
  update_period = "12h" # How often query for updates, examples: "60m", "4h", "2h45m"
  quality = "low" # or "low"
  format = "video" # or "audio"
  # custom.cover_art_quality use "high" or "low" to special cover image quality from channel cover default is equal with "quality" and disable when custom.cover_art was set.
  # custom = { cover_art = "{IMAGE_URL}}", cover_art_quality = "high", category = "TV", subcategories = ["Documentary", "Tech News"], explicit = true, lang = "en" } # Optional feed customizations
  # max_height = 720 # Optional maximal height of video, example: 720, 1080, 1440, 2160, ...
  max_height = 480
  # cron_schedule = "@every 12h" # Optional cron expression format. If set then overwrite 'update_period'. See details below
  # filters = { title = "regex for title here", not_title = "regex for negative title match", description = "...", not_description = "..." } # Optional Golang regexp format. If set, then only download matching episodes.
  # opml = true|false # Optional inclusion of the feed in the OPML file (default value: false)
  # clean = { keep_last = 10 } # Keep last 10 episodes (order desc by PubDate)
  clean = { keep_last = 100 }
  # youtube_dl_args = [ "--write-sub", "--embed-subs", "--sub-lang", "en,en-US,en-GB" ] # Optional extra arguments passed to youtube-dl when downloading videos from this feed. This example would embed available English closed captions in th                                                                                                                                                             e videos. Note that setting '--audio-format' for audio format feeds, or '--format' or '--output' for any format may cause unexpected behaviour. You should only use this if you know what you are doing, and have read up on youtube-dl's options!

[database]
  badger = { truncate = true, file_io = true } # See https://github.com/dgraph-io/badger#memory-usage

[downloader]
  self_update = true # Optional, auto update youtube-dl every 24 hours

# Optional log config. If not specified logs to the stdout
[log]
  filename = "podsync.log"
  max_size = 50 # MB
  max_age = 30 # days
  max_backups = 7
  compress = true
```

For me it looks like Podsyncs webserver doen't allow me to access the feeds. What did I wrong?

**Comment by mxpv** [comment]
Can you try accessing locally? Like `http://localhost:8080` ? 
Podsync has no auth logic, so there is something else that returns 403 error code.

**Comment by Dunuin** [comment]
I used this to roll out the docker container so 8080 inside the docker container is accessed by port 18080 from the host:
```
$ docker pull mxpv/podsync:latest
$ docker run \
    -p 18080:8080 \
    -v $(pwd)/data:/app/data/ \
    -v $(pwd)/config.toml:/app/config.toml \
    mxpv/podsync:latest
```

I also tried it with "docker run -p 18080:18080" and "port = 18080" in the config file but still the same "403 Forbidden"

**Comment by mxpv** [comment]
Try '-p 8080:8080'

**Comment by Dunuin** [comment]
The problem was that the data dir wasn't accessible (problem bind mounting a SMB share from the hypervisor to the LXC running docker). Now I can see my data folder and my testfile in it.
But it looks like podsync isn't working. The data folder is empty (except for my testfile) and there is only one log entry:
`time="2020-10-13T22:40:19Z" level=info msg="\n _______  _______  ______   _______           _        _______ \n(  ____ )(  ___  )(  __  \\ (  ____ \\|\\     /|( (    /|(  ____ \\\n| (    )|| (   ) || (  \\  )| (    \\/( \\   / )|  \\  ( || (    \\/\n| (____)|| |   | || |   ) || (_____  \\ (_) / |   \\ | || |      \n|  _____)| |   | || |   | |(_____  )  \\   /  | (\\ \\) || |      \n| (      | |   | || |   ) |      ) |   ) (   | | \\   || |      \n| )      | (___) || (__/  )/\\____) |   | |   | )  \\  || (____/\\\n|/       (_______)(______/ \\_______)   \\_/   |/    )_)(_______/\n"`

**Comment by mxpv** [comment]
Thanks for the update! Closing this one.
