### ISSUE TITLE
Feature Request: Set feed as private

### ISSUE THREAD

**Issue by jonchampagne** [mxpv/podsync#188]
Recently it seems some of my feeds have been indexed by a couple of podcasting apps, including pocket casts and overcast. It would be nice to be able to enable the `<itunes:block>` and `<googleplay:block>` tags, to prevent the feeds from getting indexed.

**Comment by mxpv** [comment]
Docs:
http://support.megaphone.fm/en/articles/2700280-itunes-and-google-block-tags
https://support.google.com/podcast-publishers/answer/9889544?hl=en
