### ISSUE TITLE
something wrong when i play in pocketcasts

### ISSUE THREAD

**Issue by fishyo** [mxpv/podsync#189]
hi max:

1. I build server with docker and it run success,some episodes also download succeed in the data files
2.my pocktcasts also subscried succeed
3.but when i play with steaming or download the podcast,it faild

**Comment by sean89503** [comment]
Pocket cast is a little tricky. But I got mine to work. Pocket cast is a server side client period so you need to make sure that is visible from outside of your network at all times. If you've already done that and it still fails it might be because you need to set a custom DNS on your local network to point to your server. I achieved this by using a raspberry pi with PIHole

**Comment by fishyo** [comment]
> 
> 
> Pocket cast is a little tricky. But I got mine to work. Pocket cast is a server side client period so you need to make sure that is visible from outside of your network at all times. If you've already done that and it still fails it might be because you need to set a custom DNS on your local network to point to your server. I achieved this by using a raspberry pi with PIHole

for example:my sever ip is ：192.168.1.1，so i need point a dns adress to 192.168.1.1. is that right？

**Comment by sean89503** [comment]
In your config file set you proxy to your ddns.

Then is your local DNS add you ddns address as feed.ddns.com 192.168.1.??

Make sure that your port it open on your firewall and you should be set. 

What nice about using a ddns is that you can move your server and it won't mess with your feed.

**Comment by lxyer** [comment]
@sean89503 @fishyo Would you please show more details

**Comment by simonv3** [comment]
For those curious I followed these steps in particular to podsync working with pocket casts:

https://gist.github.com/simonv3/69703c5732c0a08a766b4ae00e57feb1

(It's just a bit more in depth than the previous comment)
