### ISSUE TITLE
Image Preview for Podcast Episode is now lower quality

### ISSUE THREAD

**Issue by driverkt** [mxpv/podsync#197]
Hello!  This is an awesome tool! Thanks for developing it!

I've noticed that for the podcasts I've been using for quite some time, in [2.4.0](https://github.com/mxpv/podsync/releases/tag/v2.4.0), the preview image as well as the episode specific images seem to be lower quality. 

I've added the following line, but it doesn't seem to be working for me: 

`custom = { cover_art_quality = "high" }`

Is that syntax correct? 

Please note that I am not specifying custom cover art but pulling it in from YouTube.

**Comment by mxpv** [comment]
Hmm.. The only change we made in v2.4.0 related to cover art quality is this one https://github.com/mxpv/podsync/commit/3572e14706a7a43dd23cc24f7c0f7174cb14ca53

But if it is not specified it should default to "high" (and `cover_art_quality = "high"` should produce the same result)

Can you provide full configuration for this channel ?

**Comment by driverkt** [comment]
something like this: 

`[feeds.dude-perfect]
  url = "https://www.youtube.com/channel/UCRijo3ddMTht_IHyNSNXpNQ" # URL address of a channel, group, user, or playlist. 
  page_size = 5 # The number of episodes to query each update (keep in mind, that this might drain API token)
  update_period = "5h" # How often query for updates, examples: "60m", "4h", "2h45m"
  quality = "high" # or "low"
  format = "video" # or "audio"
  custom = { cover_art_quality = "high" }
  clean = { keep_last = 5 }`

**Comment by 726a67** [comment]
Also experiencing this issue with feed quality set to 'high' and cover_art_quality not explicitly set.

**Comment by driverkt** [comment]
@mxpv Does this help? Can you recreate the issue with this?

> something like this:
> 
> ```
> [feeds.dude-perfect]
>   url = "https://www.youtube.com/channel/UCRijo3ddMTht_IHyNSNXpNQ" # URL address of a channel, group, user, or playlist. 
>   page_size = 5 # The number of episodes to query each update (keep in mind, that this might drain API token)
>   update_period = "5h" # How often query for updates, examples: "60m", "4h", "2h45m"
>   quality = "high" # or "low"
>   format = "video" # or "audio"
>   custom = { cover_art_quality = "high" }
>   clean = { keep_last = 5 }
> ```

**Comment by 726a67** [comment]
Any update on this issue? Art pulled from Youtube channels is always resolved at 88x88 regardless of the cover_art_quality setting.

One of my feeds for reference:

```
  [feeds.Junkball]
  url = "https://www.youtube.com/channel/UCL5VhHd4v-OBLwCSvLWf70A"
  page_size = 5
  update_period = "60m"
  quality = "high"
  custom = { cover_art_quality = "high" }
  format = "video"
  max_height = 720
  cron_schedule = "0 */2 * * *"
  opml = true
  clean = { keep_last = 5 }
```
