### ISSUE TITLE
Only the first feed is regularily updated

### ISSUE THREAD

**Issue by DrMcCoy** [mxpv/podsync#198]
I've got several feeds in my config.toml, each with an update_period of 1h. However, only the first feed is updated at this frequency. All feeds are correctly polled on start-up, but afterwards the other feeds aren't checked again anymore.

**Comment by mxpv** [comment]
Could you provide more information? Configuration example, logs with `-debug` flag enabled.

**Comment by DrMcCoy** [comment]
Ah, sorry, seems like this was an artifact of an old version still lying around.

I did a clean rebuild of both podsync and the feed databases, and now it works correctly.
