### ISSUE TITLE
TOML Syntax Error when using Docker

### ISSUE THREAD

**Issue by MaxPowers1337** [mxpv/podsync#201]
I used the example config.toml and ran the docker image provided in the readme.md and get the error

`time="2020-11-25T16:35:35Z" level=fatal msg="failed to load configuration file" error="failed to unmarshal toml: line 3: field corresponding to `bind_address' is not defined in config.Server"`

When checking the config file (i copied from readme.md) with an 3rd party toml syntax checker, everything is fine.

**Comment by 726a67** [comment]
I'm fairly certain that the bind address included in the readme ("172.20.10.2") is only an example.

The default value ("*") should be sufficient for most users, so unless you have a specific need to limit podsync's listening address, you can try either setting the value explicitly or commenting out the bind_address line entirely.

**Comment by MaxPowers1337** [comment]
Sorry I forgot to mention that I replaced the bind address up of the example with "*".

**Comment by micahmo** [comment]
Looks like the `bind_address` parameter was added recently in 2751c4b8dec081a3e41c1d806170c3eed13231bf on Oct 27.

The latest Docker push was 2 months ago ([here](https://hub.docker.com/layers/mxpv/podsync/latest/images/sha256-30b3a1a15d2ed4ed4ceaa0cc99213b4ff1eff40ebef7b734e84a50abe51392c7?context=explore)).

Hard to tell _exactly_ when the Docker image was updated, but I think it's safe to say it doesn't include the new toml parameters.

**Comment by micahmo** [comment]
I've discovered the Docker image also doesn't contain some of the new `custom` attributes, such as `ownerEmail`. from 1ae7f09e0276780a043853a1d1e5c1c79732841d. Hopefully it is updated soon!

**Comment by JosephSamela** [comment]
Hi I came across this same issue. I commented out the `bind_address` line in `config.toml` and was able to proceed. Initially I used `"*"` to listen on all addresses, but omitting this line seems to default to listening on all addresses anyways.

**Comment by mxpv** [comment]
Docker image is now updated and will keep up with releases.
