### ISSUE TITLE
youtube-dl Unable to extract video from data

### ISSUE THREAD

**Issue by admun** [mxpv/podsync#202]
Starting about a week ago, all yt download failed with

time="2020-12-12T16:29:28Z" level=error msg="youtube-dl error: /tmp/podsync-515511461/unV14JDnibw.%(ext)s" error="failed to execute youtube-dl: exit status 1"
time="2020-12-12T16:29:28Z" level=error msg="[youtube] unV14JDnibw: Downloading webpage\nERROR: unV14JDnibw: YouTube said: Unable to extract video data\n"

Nothing has changed for months on this setup

How should I debug this?

**Comment by mxpv** [comment]
I believe youtube-dl needs an update

**Comment by admun** [comment]
thanks for the reply. Let me know how I can help testing/debugging

**Comment by admun** [comment]
I shell into the podsync docker container and replace youtube-dl wit https://github.com/ytdl-org/youtube-dl/releases/tag/2020.12.14

It seems to fix the issue.

**Comment by 726a67** [comment]
@admun, note that shelling into the container and manually replacing the youtube-dl binary is in all likelihood a temporary fix, as the updated binary will be lost as soon as the container is restarted.

Alternatively, Podsync can be configured to automatically update the youtube-dl binary to latest available release every 24 hours by setting the following option in your `config.toml`:

```
[downloader]
self_update = true
```

**Comment by admun** [comment]
@726a67 fully understanding that. My test is mean to confirm upstream youtube-dl fix the issue.

**Comment by admun** [comment]
@mxpv as mentioned in https://github.com/mxpv/podsync/issues/202#issuecomment-748614996

I think upstream youtube-dl fix the issue, so you should be able to rekick a new release with the latest youtube-dl to fix this issue.
