### ISSUE TITLE
bind address

### ISSUE THREAD

**Issue by geekhuashan** [mxpv/podsync#207]
Hi developers,

I am a very beginner with linux. 

I want to put the podsync into my new server(aliyun china).

When I use the vim to create the config.toml. And put the information into it

It showed the error:

INFO[2021-01-13T23:06:19+08:00]
 _______  _______  ______   _______           _        _______
(  ____ )(  ___  )(  __  \ (  ____ \|\     /|( (    /|(  ____ \
| (    )|| (   ) || (  \  )| (    \/( \   / )|  \  ( || (    \/
| (____)|| |   | || |   ) || (_____  \ (_) / |   \ | || |
|  _____)| |   | || |   | |(_____  )  \   /  | (\ \) || |
| (      | |   | || |   ) |      ) |   ) (   | | \   || |
| )      | (___) || (__/  )/\____) |   | |   | )  \  || (____/\
|/       (_______)(______/ \_______)   \_/   |/    )_)(_______/
FATA[2021-01-13T23:06:19+08:00] failed to load configuration file             error="failed to unmarshal toml: line 4: field corresponding to `bind_address' is not defined in config.Server"

I input my aliyun server IP address in it.  Or the bind_adress what I should input? And the port of My server is 80. Should I change the port 8080 to 80?

**Comment by op69qs** [comment]
最新的Releases不包含该特性，可以用最新代码进行编译。
The latest Releases does not contain this feature and can be compiled with the latest code.

**Comment by hanlihanshaobo** [comment]
Has the problem been solved? I also met

**Comment by matejdro** [comment]
See Sorry I forgot to mention that I replaced the bind address up of the example with "*".

**Comment by mxpv** [comment]
The fix is now included in v2.4.1
