### ISSUE TITLE
I can see and update feed, but not play or download any episode (Pocketcasts)

### ISSUE THREAD

**Issue by vrodriguezf** [mxpv/podsync#217]
Hi, 

I can see my feed in pocketcast, and it gets updated properly, but I cannot download or play anything. I am using Pocketcasts, and a public IP to access the server.  

Any ideas?

**Comment by vrodriguezf** [comment]
I solved by using a DDNS on top of my server (I used DuckDNS for that), and changed the field `hostname` of the configuration file to point to the duckdns address.

**Comment by simonv3** [comment]
For those curious I followed these steps in particular to podsync working with pocket casts:

https://gist.github.com/simonv3/69703c5732c0a08a766b4ae00e57feb1

(It's just a bit more in depth than the previous comment)
