### ISSUE TITLE
Most downloads seem to be failing ( error="failed to execute youtube-dl: exit status 1)

### ISSUE THREAD

**Issue by richardwarriner** [mxpv/podsync#236]
I had a few of these recently but now it seems to be everything.

It finds the download ok then spends many minutes trying to download it and eventually throwing these errors.

Runing these versions:
date="2020-10-17T23:50:21Z" version=2.4.0                1:43:26+01:00] using youtube-dl 2021.06.06
INFO[2021-10-12T11:43:26+01:00] found ffmpeg: ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the 

Error:
INFO[2021-10-12T12:53:38+01:00] downloading episodes                          page_size=30
INFO[2021-10-12T12:53:38+01:00] download count: 2
INFO[2021-10-12T12:53:38+01:00] ! downloading episode https://youtube.com/watch?v=8uLzRDExhBk  episode_id=8uLzRDExhBk index=0
ERRO[2021-10-12T13:03:38+01:00] youtube-dl error: C:\Users\server\AppData\Local\Temp\podsync-126304288\8uLzRDExhBk.%(ext)s  error="failed to execute youtube-dl: exit status 1"
ERRO[2021-10-12T13:03:38+01:00] [youtube] 8uLzRDExhBk: Downloading webpage
[download] Destination: C:\Users\server\AppData\Local\Temp\podsync-126304288\8uLzRDExhBk.f137.mp4
[download]  35.4% of 97.63MiB at 59.59KiB/s ETA 18:04
INFO[2021-10-12T13:03:38+01:00] ! downloading episode https://youtube.com/watch?v=uK-0Yndxmss  episode_id=uK-0Yndxmss index=1

**Comment by AdamCurtisVT** [comment]
In the [/pkg/ytdl/ytdl.go](https://github.com/mxpv/podsync/blob/master/pkg/ytdl/ytdl.go) file there is a constant that defines how long the download timeout is. I downloaded the source, changed it from 10 minutes to 60, and recompiled. I let it run overnight and it seems to have fixed all my issues.

`const (
	DefaultDownloadTimeout = 10 * time.Minute
        UpdatePeriod           = 24 * time.Hour
)`

**Comment by richardwarriner** [comment]
I tried this and it works at full speed https://github.com/yt-dlp/yt-dlp

I renamed the exe to youtube-dl.exe and it seems to work (for now anyway)

This project is being maintained unlike youtube-dl

**Comment by fqx** [comment]
> I tried this and it works at full speed https://github.com/yt-dlp/yt-dlp
> 

Do you know how to do this in docker.

**Comment by richardwarriner** [comment]
Sorry no - I know more about brain surgery than docker

**Comment by fqx** [comment]
Good news, I have build a working docker image with yt-dlp, get it with

`docker pull ghcr.io/fqx/podsync-with-yt-dlp:latest`

https://github.com/fqx/podsync-with-yt-dlp/pkgs/container/podsync-with-yt-dlp

**Comment by Rpsl** [comment]
https://github.com/mxpv/podsync/issues/237

**Comment by derdide** [comment]
After a bit of fiddling, I managed to properly try it with yt-dlp and I confirm the above, this works quite well. 

One question though: in the config.toml, there is a section about the downloader that proposes to update youtube-dl every 24hrs. I assume this would not work with yt-dlp - worst case, it overwrites with the normal (and older) version of youtube.dl, mid-case, it doesn't update when yt-dlp gets updated. 

So I put the option to false, but is there a way to get it to work? (I assume a wget in the crontab would do but this is not what I am looking for)

**Comment by Rpsl** [comment]
@derdide you can stay it in `true` because selfupdate doing by self binary of youtube-dl (yt-dlp in our case)

https://github.com/mxpv/podsync/blob/c1130f3f9748ce2153b29f65ecc3e065d678baaf/pkg/ytdl/ytdl.go#L122

**Comment by derdide** [comment]
@Rpsl thanks!

**Comment by streightedge** [comment]
It works partially for me. Files are beeing saved to ID1 folder and rss feed is reachable. I could add it to podcast catcher but when I try to play/download an episode i get 404 error. Any ideas why? It should work I think :)
