### ISSUE TITLE
/tmp directory 

### ISSUE THREAD

**Issue by tapatianbeast** [mxpv/podsync#243]
Hello! I have a raspberry with a micro sd card and I would like to change the option of the / tmp directory where the audios are downloaded temporary to a directory mounted on a hdd. Is it something that I could do?

**Comment by mxpv** [comment]
Try to specify `TMPDIR` environment variable with custom path.

**Comment by tapatianbeast** [comment]
that works for the binary right?

**Comment by mxpv** [comment]
Yes
