### ISSUE TITLE
Downloads don't finish

### ISSUE THREAD

**Issue by nachocab** [mxpv/podsync#246]
When I run podsync, the logs show that the first download is downloading:

```
INFO[2021-12-24T11:49:52+01:00] -> updating https://www.youtube.com/watch?v=GLHvspXLZZA&list=PL6PJg4k4pL5yIeIwXfY1qUxl-MFr7BfZS  feed_id=ID1 format=video quality=low
INFO[2021-12-24T11:49:53+01:00] downloading episodes                          page_size=50
INFO[2021-12-24T11:49:53+01:00] download count: 49
INFO[2021-12-24T11:49:53+01:00] ! downloading episode https://youtube.com/watch?v=2MCEWdUkkM4  episode_id=2MCEWdUkkM4 index=0
```

But after 1 hour, it's still like that. I don't see anything in the data directory other than the xml and opml files. Am I missing something?

**Comment by Rpsl** [comment]
see look like a problem from #237

**Comment by nachocab** [comment]
Thanks, I just `brew uninstalled youtube-dl` and `brew installed yt-dlp` and `ln -s /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl` and now it works!
