### ISSUE TITLE
What's the RSS feed URL?

### ISSUE THREAD

**Issue by ashishb** [mxpv/podsync#276]
So, I was able to configure podsync to run locally. What's the URL for the XML feed(s)? 
Is it supposed to be domain/ID1.xml? (doesn't seem to work)

**Comment by bcarney66** [comment]
Try http://localhost:**8080**/ID1.xml  And of course make sure the Docker instance is running.

**Comment by ashishb** [comment]
It seems it works only after all the episodes have been downloaded.
