### ISSUE TITLE
can not play in any podcast app

### ISSUE THREAD

**Issue by geekhuashan** [mxpv/podsync#277]
I just installed in my VPS through docker and the log showed it worked well. Also the files downloaded and also stored in my vps local storage.
![tmpC207](https://user-images.githubusercontent.com/47098938/152469450-58e61ceb-28e3-49fe-a72e-1efd90c2e1f7.png)
![tmp16CF](https://user-images.githubusercontent.com/47098938/152469557-ff24f2e0-4775-4ed3-a99c-9a92660e3944.png)
Also I can reach in the browser with the http://ip:8080
![tmpCC95](https://user-images.githubusercontent.com/47098938/152469610-79f1afe6-0504-4214-b6f2-1373e9617c5a.png)

And I also succeed to subscribe the feed in my podcast app including google podcast apple podcast overcast.

### **The only problem is I can not play the audio.**
![image](https://user-images.githubusercontent.com/47098938/152469797-ba82cfef-f5be-47b4-8eb6-a17263035e3f.png)
![image](https://user-images.githubusercontent.com/47098938/152469811-a227ac8d-8c18-4c2a-bd20-f3f000aa22c2.png)
![image](https://user-images.githubusercontent.com/47098938/152469822-f05e4e6f-7812-424d-b02f-e9303932844c.png)

I tried to reinstall the docker and reinstall the app, it also the same problem.

Any information you want i will offer.

**Comment by geekhuashan** [comment]
[server]
port = 8080
data_dir = "/app/data" # Don't change if you run podsync via docker


# Tokens from `Access tokens` section
[tokens]
youtube = "mytoken"

[feeds]
  [feeds.ID1]
  url = "https://www.youtube.com/channel/UC_5lJHgnMP_lb_VpIiXV0hQ" 
  page_size = 5 
  update_period = "6h" 
  quality = "high"
  format = "audio" 



[database]
  badger = { truncate = true, file_io = true }

[downloader]
self_update = true # Optional, auto update youtube-dl every 24 hours
timeout = 15 # Timeout in minutes

**Comment by bcarney66** [comment]
I found that on my system the <enclosure url  value in the ID1.xml file is set to localhost and I get the 'temporarily unavailable message' when I try to stream on my LAN.   My machine's IP address is 192.168.168.123.  If I search and replace localhost:8080 with 192.168.168.123:8080  in the XML files I'm then able to stream the files to my mobile devices.  That said, I'm streaming video to the Podcasts app on my iPad. I have not been successful in getting audio to my iPhone and Overcast - in fact, you've gotten farther along than have, I can't even get Overcast to recognize any of the feeds generated by podsync.

**Comment by AdamCurtisVT** [comment]
I believe you need to set the server hostname property in the config.toml file. If you don't, all the feeds will have localhost which won't be accessible from anything other than the server itself. 

```
[server]
port = 8080
hostname = "https://my.test.host:4443"
```
