### ISSUE TITLE
make: *** No rule to make target 'build'.  Stop.

### ISSUE THREAD

**Issue by bradleyjohnsen** [mxpv/podsync#30]
Recreation Steps:
From root directory, run sudo make build

Expected result:
Build logic from Makefile

Result:
make: *** No rule to make target 'build'.  Stop.

See attached screenshot.
![podsync make build error](https://user-images.githubusercontent.com/405256/62000727-3580ae80-b0ac-11e9-987f-265c11fe8c0f.png)

It looks like there is no build command in Makefile currently.

SUBDIRS := cmd/api cmd/nginx
BINPATH := $(abspath ./bin)
GOLANGCI := $(BINPATH)/golangci-lint

.PHONY: push
push:
	for d in $(SUBDIRS); do $(MAKE) -C $$d push; done

$(GOLANGCI):
	curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(BINPATH) v1.17.1
	$(GOLANGCI) --version

.PHONY: lint
lint: $(GOLANGCI)
	$(GOLANGCI) run

.PHONY: test
test:
	go test -short ./...

.PHONY: up
up:
	docker-compose pull
	docker-compose up -d

**Comment by BHAVISHYA2005** [comment]
This is oftenly not a build error, basically you are into a wrong path where you are running a make command. Hope it helps 👍🏻
