### ISSUE TITLE
Feature request: Just in time downloading/episode streaming

### ISSUE THREAD

**Issue by distributed01** [mxpv/podsync#300]
Hi I was wondering whether the ability for Podsync to download episodes just in time from youtube and delete them afterwards has been considered. 

I.e it would download and permanently store all video lists for all channels (same behaviour as now) as they do not take up much space, but would only download videos when they are requested and stream the contents to the client as it is being downloaded.

The rationalise for this is that storage space (of which Podsync for me, uses about 90GB) is much more expensive when renting a VPS than is bandwidth. Bandwidth for even very cheap VPS servers is extremely fast and is usually unmetered, so therefore the ability to stream episodes on the fly would significantly reduce the cost of using Podsync with lots of channels in the "video" format.

I find downloading in video rather than audio necessary and very useful as most of the channels I subscribe to use whiteboards or visualisations, making audio insufficient by itself.

Thanks for considering this.

**Comment by lukas-mertens** [comment]
@distbit0 Hey, I just found your issue, as I was looking for the same thing. Why did you close it? Did you find a way to achieve your goal?

**Comment by distbit0** [comment]
Hey yeah @lukas-mertens I decided it was easier to just run podsync on a local raspberry pi connected to a 1TB external ssd, hence significantly reducing my data storage costs compared to if I were to have used a VPS.
