### ISSUE TITLE
Where to obtain podsync_lambda

### ISSUE THREAD

**Issue by victor** [mxpv/podsync#31]
Totally docker newbie here, so I maybe asking something obvious.
When I try to pull images, I get this error message:

```
ERROR: for resolver  pull access denied for mxpv/podsync_lambda, repository does not exist or may require 'docker login'
```

If I am expected to generate my own image and push it to my own registry, can you share a quick recipe for accomplishing this?

thanks

**Comment by mxpv** [comment]
It's here https://github.com/mxpv/podsync/tree/master/cmd/lambda
You'll need to deploy a separate container for lambda proxy.

Its probably would be easier to run a container with resolver directly (without lambda + proxy), but it'll need a small contribution with switcher.

**Comment by mxpv** [comment]
this will be simplified here https://github.com/mxpv/podsync/issues/38
