### ISSUE TITLE
Title of video is "_"

### ISSUE THREAD

**Issue by justinormont** [mxpv/podsync#33]
Video title is being returned as "_" (an underscore).

```xml
...
<item>
      <guid>https://dl.podsync.net/download/pzyl/T-lBMrjZ3_0.mp4</guid>
      <title>_</title>
      <link>https://www.youtube.com/watch?v=T-lBMrjZ3_0</link>  
...
```

Example:
https://podsync.net/pzyl

As displayed in iTunes:
![image](https://user-images.githubusercontent.com/4080826/62325085-c4504b00-b45f-11e9-8537-0c8c90c27488.png)

**Comment by dizziness1138** [comment]
Same issue here. Also, on 07/30/19 and 07/31/19, my feed was filled with old posts.

**Comment by dpk4g** [comment]
Same issue too.
And i wonder know how to just get audio only.
![Snipaste_2019-08-02_17-28-19](https://user-images.githubusercontent.com/52632965/62390592-3f674d80-b595-11e9-8988-7a7c5915784b.png)
![Snipaste_2019-08-02_17-31-50](https://user-images.githubusercontent.com/52632965/62390604-42fad480-b595-11e9-9275-64eba5a60c9d.png)

**Comment by 726a67** [comment]
Can confirm same issue affecting titles on Pocket Casts 7.4 on iOS.

**Comment by shnorb** [comment]
Same here on Android 10b4

**Comment by mxpv** [comment]
Should be resolved for new episodes.
