### ISSUE TITLE
Unsupported Link Format

### ISSUE THREAD

**Issue by Rumik** [mxpv/podsync#347]
Hi there. I've noticed an issue recently with youtube channel names - PodSync doesn't seem to support it anymore. The error I'm seeing is: level=error msg="failed to update feed: https://www.youtube.com/AndyCortezStreams" error="update failed: failed to parse URL: https://www.youtube.com/AndyCortezStreams: unsupported link format"

If I happen to know the YouTube username, I can replace the channel name with that and it works, but in this case I don't know the username.

I've tried the format used in the example config file - https://www.youtube.com/channel/CHANNEL_NAME_TO_HOST - but that doesn't work either.

Hope you can help.

Thanks

**Comment by bcarney66** [comment]
Go to https://commentpicker.com/youtube-channel-id.php and paste the URL in and it will give you the channel ID, then use the format https://www.youtube.com/channel/UCw7gK37wUfNw3yh-_V8tkHw (the latter part after channel/ being the ID) to subscribe.

**Comment by Rumik** [comment]
I didn't see this comment! Thanks so much for this, it worked perfectly!
