### ISSUE TITLE
Some Episodes Won't Download

### ISSUE THREAD

**Issue by PaleZer0** [mxpv/podsync#36]
I am having an issue where some episodes in a feed won't ever download. This has been happening to only certain episodes for about two weeks now. I've tried generating new versions of the feeds and different ways of downloading them and the problem persists, always with the same videos while others work fine.

What happens is they sit and try to download for an extended period of time, never make progress, and then eventually error out.

The Tested Youtube channel has multiple examples: https://podsync.net/1q6W2ZNf5

Specifically, the (currently most recent) episode titled "Cutting it Close - Still Untitled: The Adam Savage Project" is one of the ones that won't download.

**Comment by ermanitu** [comment]
Same problem here. Tying this channel: https://podsync.net/yZ2bxVhE-

**Comment by leekillough** [comment]
Same here for about a week: https://podsync.net/vpVCFYhzV

It happens around 9/10 times. Rarely, a download goes through. Most of the time, it gets Error 429:

> ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by ); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I only need the audio, not the video. Right now I'm using other podcast sources, which unfortunately concatenate multiple episodes into one. To get the individual episodes, I must go to YouTube directly.

**Comment by mxpv** [comment]
issue to track: https://github.com/mxpv/podsync/issues/38
