### ISSUE TITLE
Feeds Aren't Updating

### ISSUE THREAD

**Issue by PaleZer0** [mxpv/podsync#37]
None of my feeds are updating at this point. If I recreate them it will pull the more recent episodes, but then those recreated ones won't update either.

**Comment by iHack3x2** [comment]
Same here, last updated feed for me was October the 3rd and no real feedback on what's the problem/issue, so I could at least be understanding, honestly makes me feel as if there isn't going to be a solution.

**Comment by scottkuhl** [comment]
From the PodSync Twitter account:

Hello. YT is still blocking Podsync’s servers every time and I couldn’t find a way to bypass this and make it work stable considering amount of traffic we handle. Also I no longer can invest so much time in this project, apologies for not being able to answer all support requests

**Comment by iHack3x2** [comment]
@scottkuhl thanks for the update, I wished this information was on the Podsync website or the Patreon. 

If I might ask when was that tweet sent?

**Comment by jeremytm** [comment]
I previously used this, as well as youtube.videodeck.net... Both are now unavailable. Likely permanently. This is due to Youtube blocking more features from 3rd parties and keeping as many people as possible within youtube.com.

It's quite a shame, since it allows them to have more control over what they suggest to you, what they hide from you, etc. Hopefully they are doing this to protect against malicious agendas rather than to support their own.

**Comment by scottkuhl** [comment]
> @scottkuhl thanks for the update, I wished this information was on the Podsync website or the Patreon.
> 
> If I might ask when was that tweet sent?

October 16th

**Comment by scottkuhl** [comment]
> I previously used this, as well as youtube.videodeck.net... Both are now unavailable. Likely permanently. This is due to Youtube blocking more features from 3rd parties and keeping as many people as possible within youtube.com.
> 
> It's quite a shame, since it allows them to have more control over what they suggest to you, what they hide from you, etc. Hopefully they are doing this to protect against malicious agendas rather than to support their own.

I think it has everything to do with ads not being included in the downloads.

**Comment by iHack3x2** [comment]
@scottkuhl @jeremytm yeah I can totally see why YouTube would be against this in the first place, it might be convenience for them but it isn't for me. I use a third party RSS reader and it allows me to just search who's in my feed including the description and it keeps me from getting sucked into the abyss that is YouTube. 

But YouTube has naive RSS feeds, I might just go back to that. It just sucks that only like 10-15 are allowed at the start of the feed creation. I definitely would pay them a few extra bucks to be able to get an entire channels catalog into an RSS feed and allowed above 720p for streaming outside of Youtube.com.

**Comment by scottkuhl** [comment]
My backup plan has been going back to Feedly and using the RSS feed as well. I wish someone like PocketCasts would support YouTube channels. I understand they can't download the videos but they should be able to stream them.

**Comment by focuspulling** [comment]
@scottkuhl It's highly unethical for you to continue collecting money via Patreon; it's publicly reported that you are collecting $620 per month, and yet you have ignored all messages there from actual paying patrons like myself.  I have asked Patreon admins to take appropriate enforcement action.

**Comment by scottkuhl** [comment]
@focuspulling 

Just to be clear, I am not the developer of PodSync.  I am also a user.  Just trying to inform others.  I agree, if the site is no longer going to work and the developer has no plans on fixing it, the Patreon should be stopped.

**Comment by focuspulling** [comment]
@scottkuhl Hi Scott, really sorry about the misunderstanding. I had missed the central fact that you took initiative here at GitHub as a separate open source endeavor after Maksym Pavlenko abandoned PodSync while continuing to collect money.  I'm already pursuing a complaint at Patreon and will make sure he stops profiting now that there is no continued service as promised.  Meantime, I edited my comment above to avoid confusion.

I think I'm going to give Inoreader a go, which (at a somewhat reasonable Pro subscription) can accomplish this in combination with IFTTT.

**Comment by mxpv** [comment]
Podsync is still running at Podsync.net and handles download requests. And I still pay for the underlying resources. I don’t want to just shut it off as many people rely on it.

**Comment by scottkuhl** [comment]
@mxpv interesting. I thought YouTube was blocking it.  How are users still relying on it?

**Comment by mxpv** [comment]
@scottkuhl Many users use Podsync to distribute podcasts (for example as a source URL for iTunes podcasts). Blocking part is related to episode downloader.

**Comment by mxpv** [comment]
> Feeds Aren't Updating

issue to track https://github.com/mxpv/podsync/issues/38
