### ISSUE TITLE
New release or nightly tag?

### ISSUE THREAD

**Issue by amardeepsingh** [mxpv/podsync#394]
@mxpv How often do you do releases? I see that it has been a while since the last one, and there are a couple of fixes that I'm blocked on that I would love to have a new release for. Alternatively, a docker image with a nightly tag would be nice for people that like to be on the latest and greatest.

**Comment by mxpv** [comment]
Will do!

**Comment by mxpv** [comment]
Done: https://github.com/mxpv/podsync#nightly-builds
