### ISSUE TITLE
Downloaded files are mp3 but feed contains reference to m4a

### ISSUE THREAD

**Issue by bartlibert** [mxpv/podsync#41]
I have set up my own self-hosted version to track a youtube channel.
I've set it up as "low quality audio". I see that the episodes are downloaded in mp3 format.
However, the resulting xml-file for the feed contains references to m4a files, hence the feed does not work in my podcast app, because it fails with "file not found". The filenames are correct, just the extsenion is wrong.

Podsync version:  commit=7c1b1046f19fee5fa85bb34c0f7edec7013d55f7 date="2019-11-14T06:56:06Z" version=2.0.1
using youtube-dl 2019.01.17
using ffmpeg ffmpeg version 4.1.4-1~deb10u1

**Comment by wanxj119** [comment]
the same question.

**Comment by mxpv** [comment]
Fixed.
