### ISSUE TITLE
Feed xml does not contain the custom port number

### ISSUE THREAD

**Issue by richardwarriner** [mxpv/podsync#43]
I am running the CLI on port 8421 but the xml feed generated doesn't include this in the path to the video.
This generate a not found error when i try to play it

So

http://mydomain.homeip.net/TryChannel/IWihhlAW-2s.mp4

need to be

http://mydomain.homeip.net:8421/TryChannel/IWihhlAW-2s.mp4

**Comment by richardwarriner** [comment]
Realised that i can add this to the url in the config which then carries through to the xml

**Comment by mxpv** [comment]
Fixed. Rolling out 2.0.2

**Comment by mxpv** [comment]
@richardwarriner you'd need to specify `hostname=http://mydomain.homeip.net:8421` in the upcoming update
