### ISSUE TITLE
Amazon one click deployment not working

### ISSUE THREAD

**Issue by mattiasJohnson** [mxpv/podsync#450]
The one-click deployment does not seem to work. Firstly the pre-set link in the aws setup page to `cloud_formation.yml` does not work (allaccessdenied) so I just used the `cloud_formation.yml` file in this repo. After providing my API key and youtube playlist and running the cloud formation it does not work. I ssh'ed into the ec2 instance and the docker log is giving me

```
time="2022-11-12T16:02:22Z" level=fatal msg="failed to load configuration file" error="1 error occurred:\n\t* data directory is required\n\n"
time="2022-11-12T16:02:22Z" level=fatal msg="failed to load configuration file" error="1 error occurred:\n\t* data directory is required\n\n"
time="2022-11-12T16:02:23Z" level=fatal msg="failed to load configuration file" error="1 error occurred:\n\t* data directory is required\n\n"
time="2022-11-12T16:02:24Z" level=fatal msg="failed to load configuration file" error="1 error occurred:\n\t* data directory is required\n\n"
time="2022-11-12T16:02:26Z" level=fatal msg="failed to load configuration file" error="1 error occurred:\n\t* data directory is required\n\n"
time="2022-11-12T16:02:28Z" level=fatal msg="failed to load configuration file" error="1 error occurred:\n\t* data directory is required\n\n"
```

**Comment by SarahJeanEwing** [comment]
I know this post was week ago, but did you ever get it to work?

**Comment by mattiasJohnson** [comment]
Unfortunately not :/ The whole point of a one click deployment is for it to be seamless so it seems to be a fairly important issue, hopefully someone who knows can fix it/give guidance

**Comment by SarahJeanEwing** [comment]
I was able to make it work yesterday.  The cloud_formation.yml file that is currently available has some flaws that make it not work well.  I wrote this up in the discussions section.  Maybe it will get it closer to working for you!  https://github.com/mxpv/podsync/discussions/471

**Comment by mattiasJohnson** [comment]
Thanks a lot! I tried your solution and it worked wonderfully
