### ISSUE TITLE
"http://" and port number forced on feed xml addresses

### ISSUE THREAD

**Issue by bartlibert** [mxpv/podsync#47]
I have podsync running on my own server behind nginx, with https enabled.
This means it is available at "https://podsync.myserver.net". However, the xml feed contains references to "http://podsync.myserver.net:9090/", which does not work for two reasons: it does not use ssl, which is required on my server + port 9090 is not exposed, the "podsync" subdomain just redirects to it.

**Comment by mxpv** [comment]
That's the opposite to https://github.com/mxpv/podsync/issues/43
Probably `port` and `hostname` should be independent.
So it'd be possible to cover both cases:
```
port=8080
hostname=http://myserver:8080
```
and for cases with frontend
```
port=8080
hostname=https://myserver.net (nginx redirects to `http://localhost:8080`)
```

It might also make sense to embed https functionality (for instance with automatic Let's encrypt).

**Comment by bartlibert** [comment]
This seems a good solution. Maybe make the builtin Let's encrypt support optional, as it might interfere with nginx encryption (not sure?)?

**Comment by mxpv** [comment]
@bartlibert for sure, it must be optional
