### ISSUE TITLE
Wrong audio format

### ISSUE THREAD

**Issue by danieleugoletti** [mxpv/podsync#50]
I use the docker version to generate a feed from youtube channel in audio format (quality = "high" format = "audio"), the files are stored in a folder (data_dir="/app/data/") and have the right name and extension (.mp3), but the files aren't mp3 anche can't be played.

I made some test in macOS and the error seams in youtube-dl

this command produce wrong file:
youtube-dl --extract-audio --audio-format mp3 --format bestaudio --output data/abc/TA-c16e_zZ8.mp3 https://youtube.com/watch\?v\=TA-c16e_zZ8

this command without output param produce the right mp3 but in wrong location:
youtube-dl --extract-audio --audio-format mp3 --format bestaudio https://youtube.com/watch\?v\=TA-c16e_zZ8

**Comment by tuxpeople** [comment]
In my case, content was WebM, not MP3.

**Comment by danieleugoletti** [comment]
I'm not RSS export, podsync generate audio in webm but in the RSS there is 

<enclosure url=".....hdyh1pRaUO0.mp3" length="28511277" type="audio/mpeg"></enclosure>

it's correc?, seems strange

The workaround that I found is to change the --output param in youtube-dl  with .webm extension:

youtube-dl --extract-audio --audio-format mp3 --format bestaudio --output data/abc/TA-c16e_zZ8.webm https://youtube.com/watch\?v\=TA-c16e_zZ8

in this case youtube-dl download the file in data/abc/TA-c16e_zZ8.webm and  convert it to data/abc/TA-c16e_zZ8.mp3

**Comment by hzenginx** [comment]
Glad someone else found this. podsync uses `--output` in the wrong way. See: https://github.com/ytdl-org/youtube-dl/issues/16357
