### ISSUE TITLE
Creating nfo files....- a bit of a different direction.

### ISSUE THREAD

**Issue by psyciknz** [mxpv/podsync#51]
Runing podsync as docker.

When I run it, I see it downloads all the mp4 files.....so i naturually thought, hmm maybe I can put these in plex as a library.   The easiest way I can think of doing this, is for each media file to add an nfo file.

i don't know go to save myself, but if I hacked around inside the container and added a method like buildpodcast (in updater.go) for nfo, and wrote out a new file each time, would it run (ie like python does), or is go compiled like c, So I'd have to rebuild the image?

**Comment by mxpv** [comment]
Can you give more context here, since I'm not familiar with Plex platform? 
How do you generate nfo files? Does Plex needs XML feeds or just a directory with mp4/nfo files?

**Comment by psyciknz** [comment]
Plex (or kodi, or emby) would want the mp4 files and a matching nfo file.  The NFO file contains the metadata (similar to what is provided in the <showname>.xml for each episode.    It might be too much of a departure from your current architecture.

**Comment by mxpv** [comment]
How do you generate metadata?

On Nov 21, 2019, at 11:42 AM, psyciknz <notifications@github.com> wrote:

﻿

Plex (or kodi, or emby) would want the mp4 files and a matching nfo file. The NFO file contains the metadata (similar to what is provided in the .xml for each episode. It might be too much of a departure from your current architecture.

**Comment by psyciknz** [comment]
They're a common file format....
```
<?xml version='1.0' encoding='UTF-8'?>
<episodedetails>
  <title>Starling City</title>
  <showtitle>Arrow</showtitle>
  <season>8</season>
  <episode>1</episode>
  <uniqueid>7249300</uniqueid>
  <aired>2019-10-15</aired>
  <plot>While trying to decipher The Monitor’s mission, Oliver returns to Starling City where he encounters familiar faces. Meanwhile, Mia and William’s team clash with a new foe.</plot>
  <runtime>45</runtime>
  <thumb>http://thetvdb.com/banners/episodes/257655/7249300.jpg</thumb>
  <credits>Beth Schwartz</credits>
  <credits>Marc Guggenheim</credits>
  <director>James Bamford</director>
</episodedetails>
```


Buit I think I might do what I want another way, surely there's already a project to pull files form youtube into plex..... Thanks anyway.
