### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by tuxpeople** [mxpv/podsync#52]
Does it clean up old episodes to save space? Documentation says nothing regarding cleanup. And if so, is it configurable? If not, it may be worth to add this feature. And make it configurable. best would be to be able to configure max files and max size per feed. If configured both, the first one hit would be effective. Global would also be nice.

**Comment by mxpv** [comment]
Hey. It's not supported, but planned. There is a discussion started in https://github.com/mxpv/podsync/issues/44. Feel free to leave your thoughts there. I'm going to close this to keep the discussion in one place.
