### ISSUE TITLE
How to stop docker container/program when download has completed?

### ISSUE THREAD

**Issue by PylotLight** [mxpv/podsync#546]
I've setup podsync in a GitHub actions pipe to run on a schedule to download files and push to an s3 bucket. One of the issues I ran into is that it's designed to run like a continuous server rather than a triggered single-use application to be run on a schedule. Is there any flags or controls that can be used to end the server once download/upload is complete?

p.s I do have a workaround by timing out the step and adding continue on error, but this is not ideal and just thought I'd ask.

**Comment by Harnas** [comment]
Just run with `--headless` parameter.

**Comment by PylotLight** [comment]
@Harnas I tried and got "unknown flag: --headless"
"Run addnab/docker-run-action@v[3](https://github.com/PylotLight/demopodsync/actions/runs/5988846112/job/16244442679#step:4:3)
  with:
    image: mxpv/podsync:latest
    options: -e PODSYNC_CONFIG_PATH=config/config.toml -e AWS_ACCESS_KEY_ID=*** -e AWS_SECRET_ACCESS_KEY=*** -v /home/runner/work/demopodsync/demopodsync/data:/app/data -v /home/runner/work/demopodsync/demopodsync/config:/app/config --headless"
