### ISSUE TITLE
How to support links

### ISSUE THREAD

**Issue by lxyer** [mxpv/podsync#583]
How to support links in the format https://www.youtube.com/@bulianglin?

**Comment by sean89503** [comment]
I usually use [socialblade](https://socialblade.com/) if you search for the channel and then click on the youtube icon it goes to the channel URL so for the example above it gave [https://www.youtube.com/channel/UCbCCUH8S3yhlm7__rhxR2QQ](https://www.youtube.com/channel/UCbCCUH8S3yhlm7__rhxR2QQ)

**Comment by lxyer** [comment]
> I usually use [socialblade](https://socialblade.com/) if you search for the channel and then click on the youtube icon it goes to the channel URL so for the example above it gave https://www.youtube.com/channel/UCbCCUH8S3yhlm7__rhxR2QQ

thx
