### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by tuxpeople** [mxpv/podsync#60]
Is there anywhere a CHANGELOG to see which version include which fixes?

I'm wondering if docker image v2.0.5 contains merge #59.

**Comment by mxpv** [comment]
> Is there anywhere a CHANGELOG to see which version include which fixes?

Yes, it's here: https://github.com/mxpv/podsync/releases

> I'm wondering if docker image v2.0.5 contains merge #59.

Not yet.
