### ISSUE TITLE
Help installing locally?

### ISSUE THREAD

**Issue by mmarfil** [mxpv/podsync#62]
Hello there 👋.

Could someone here possibly help a noobie set up Podsync to run locally? I'm _reasonably_ familiar with macOS Terminal, but I have no idea how to proceed with the installation. I've never used Docker before, and not sure exactly what are the exact steps to get everything running.

For what is worth it, I'm running macOS Catalina and I'd appreciate any help. 🙂

**Comment by Rumik** [comment]
Me too- Linux-based QNAP NAS user here! THANKS!

**Comment by kgraefe** [comment]
@mmarfil The CLI binary ([Podsync_2.0.6_Darwin_x86_64.tar.gz][3] for macOS) does not require Docker. Install [Homebrew][2] and follow [podsync's README][1]. If that does not work for you, I'm afraid we need more details to help you out.

[1]: https://github.com/mxpv/podsync#dependencies
[2]: https://brew.sh/
[3]: https://github.com/mxpv/podsync/releases/download/v2.0.6/Podsync_2.0.6_Darwin_x86_64.tar.gz

**Comment by Rumik** [comment]
I don't suppose anyone knows how to compile a linux binary into a QNAP compatible binary?

**Comment by mxpv** [comment]
@Rumik as far as I understand it runs Docker? So you don't need to compile and build CLI, instead it should be as simple as: 
```
$ docker pull mxpv/podsync:latest
$ docker run \
    -p 8080:8080 \
    -v $(pwd)/data:/app/data/ \
    -v $(pwd)/config.toml:/app/config.toml \
    mxpv/podsync:latest
```

**Comment by Rumik** [comment]
Hi there,

I cannot find a way to use Docker via the command line on QNAP - it requires the installation of an app called Container Station that has a UI for adding and managing images. So far all my attempts to get PodSync installed on it have failed :(

**Comment by Rumik** [comment]
I've managed to get the docker image installed on my QNAP, and I've sorted out a YouTube API, but I have no idea what to do next. I'm not a developer :(

**Comment by Rumik** [comment]
Okay, so I'm getting this error when running the image: FATA[2019-12-10T09:20:09Z] failed to load configuration file             error="failed to load config file: open config.toml: no such file or directory"

**Comment by mxpv** [comment]
@Rumik you need to create a configuration file, where you actually specify what feeds you're going to host. 
This line from above tells Docker where exactly to find config file:
```
-v /full/path/to/your/config.toml:/app/config.toml \
```

**Comment by Rumik** [comment]
Thank you- is that what I need to type in the docker terminal in order to create the config file?

**Comment by mxpv** [comment]
@Rumik It's just a regular text file, it's not necessary to create it from terminal.

**Comment by Rumik** [comment]
i guess I just need to figure out how to get the config file onto the container once I’ve created it 😬

**Comment by mxpv** [comment]
This is what `-v /full/path/to/your/config.toml:/app/config.toml ` does. You just need to put your config file at `/full/path/to/your/config.toml`

**Comment by Rumik** [comment]
I appreciate the help... I'm getting closer. 

So here's what I've done. I installed Container Station on my QNAP, and I SSH'd into my QNAP using putty. I ran all the commands to create the docker image, which created a container for it. I'm trying to set the container into Bridge mode so it can get access to the internet, but the container won't start.

![image](https://user-images.githubusercontent.com/1244121/70789272-9d4d4280-1d8a-11ea-854c-0977ee2c138b.png)

Any ideas?

Thanks!

**Comment by Rumik** [comment]
I guess what I'm struggling with is how to get the config file onto the container.

**Comment by Rumik** [comment]
So I'm getting further, but still having problems. I've used the commands above to install the image and create a container, but shortly after the container starts it then stops, complaining that it can't find the config file. I've got the config.topl file stored on my NAS at /share/CACHEDEV1_DATA/appdata/podsync/config/config.toml but I'm still confused about how to tell podsync that the config file is in that folder. Do I SSH into the container when it's active? Do I SSH onto the NAS? A friendlier step-by-step guide would be really appreciated.

Thanks!

**Comment by kgraefe** [comment]
Try Step 5 from [here](https://github.com/marcoraddatz/homebridge-docker/wiki/Installation-via-QNAP-(GUI)) with `Volume from host: /share/CACHEDEV1_DATA/appdata/podsync/config/config.toml`  and `Mount Point: /app/config.toml`.

(I'm not a docker expert nor do I have any experience with the QNAP NASes. I am just googling around.)

**Comment by Rumik** [comment]
Sadly no that doesn't work - you can't add a file as a mount point, only a directory :( Appreciate you trying tho!

**Comment by Rumik** [comment]
Ooh I've got a bit further... setting up the container by running the commands, it wasn't clear that I should be replacing 

-v $(pwd)/data:/app/data/ \
-v $(pwd)/config.toml:/app/config.toml \

with 

-v $(pwd)/data:/share/CACHEDEV1_DATA/appdata/podsync/episodes/ \

-v $(pwd)/config.toml:/share/CACHEDEV1_DATA/appdata/podsync/config/config.toml \


So that looks right now... but the container is complaining about networking issues.

**Comment by Rumik** [comment]
I'm getting closer! I changed the port number and podsync is now running, but it's still complaining about not being able to find the config file.

I'm hosting the config file on my NAS... how do I give the docker image access to the right folder?

if I'm not supposed to have the config file and data on the NAS... how do I put the config file on the docker image?

**Comment by Rumik** [comment]
Okay, nearly there!

I've got PodSync running on the docker image, I've got the config and data directories set. Episodes are successfully downloading.... somewhere! I can't find them! They're not in the folder I've specified as the data folder! So where are they?!

**Comment by Rumik** [comment]
Hey again!

I am SO close! I've got podsync working, it's downloading episodes, it's creating the XML files and I'm even able to access them from outside my network (I use a dynamic dns on my qnap, which redirects from a custom url to the qnap), but the download links in the XML are for localhost... not the ip address of my qnap, but critically not the custom domain, even though I have entered it as the hostname in my config file.

How can I get the XML files to change the download links to the custom URL?

Thank you! I'm re-backing right now :)

**Comment by mxpv** [comment]
@Rumik would you be interested in writing a how to guide for QNAP?

**Comment by Rumik** [comment]
Yeah, I' dbe happy to write a guide! Where shall I send it?

**Comment by mxpv** [comment]
@Rumik you can open a PR here or open an issue with [attached](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) file.

**Comment by Rumik** [comment]
One thing before I write the guide... the downloaded episodes aren't in the data folder specified in the config file or when I installed the image. I have no idea where they are!

**Comment by mxpv** [comment]
> -v /share/CACHEDEV1_DATA/appdata/podsync/episodes:/app/data/ 
> -v /share/CACHEDEV1_DATA/appdata/podsync/config/config.toml:/app/config.toml \

@Rumik  Do you see them at `/share/CACHEDEV1_DATA/appdata/podsync/episodes` ?

**Comment by Rumik** [comment]
Hey - no, I don't. I see them all in /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2

**Comment by Rumik** [comment]
Here's the guide. It's pretty barebones, but it should be enough to help anybody facing the same issues I did! 
[PodSync for QNAP Guide.txt](https://github.com/mxpv/podsync/files/3978121/PodSync.for.QNAP.Guide.txt)

**Comment by mxpv** [comment]
@Rumik thank you so much for doing this! The guide available [here](https://github.com/mxpv/podsync/blob/master/docs/how_to_setup_podsync_on_qnap_nas.md).

**Comment by Rumik** [comment]
Thank YOU for providing PodSync! It makes me very happy! Writing a guide is the least I can do to show my appreciation!
