### ISSUE TITLE
Resume youtube download

### ISSUE THREAD

**Issue by Fullmono** [mxpv/podsync#67]
Hi, 

I regularly have error while downloading youtube videos: 

> failed to execute youtube-dl: signal: killed

As a result, the podcast feed is not updated. When I restart podsync, the episode is considered to be already downloaded. I have to delete the file manually to re-download it.

**Comment by mxpv** [comment]
Is there a reason why it's being killed?

**Comment by Fullmono** [comment]
I don't know, this is not intentional. It happens regularly on longest video's.
I'm running on a raspberry pi 3.
