### ISSUE TITLE
It doesn't download any videos (docker)

### ISSUE THREAD

**Issue by pblgomez** [mxpv/podsync#69]
I'm trying the docker-compose and starts up ok but it doesn't download any videos, I can see the webserver that generates with the xml and the folder but nothing inside the folder.

### config.toml
`[server]
port = 8080
data_dir = "/app/data"

[tokens]
youtube = "XxXXXxXXXxXXxXxxxxXXxxxxXXxxXxxxXx" # hidden for posting
vimeo = "{VIMEO_API_TOKEN}"

[feeds]
  [feeds.Pine64]
  url = "https://www.youtube.com/channel/UCs6A_0Jm21SIvpdKyg9Gmxw/videos"
  page_size = 10 # The number of episodes to query each update (keep in mind, that this might drain API token)
  update_period = "5m" # How often query for updates, examples: "60m", "4h", "2h45m"
  quality = "high" # or "low"
  format = "video" # or "audio"
`
### output
`
Creating network "podsync_default" with the default driver
Creating podsync ... done
Attaching to podsync
podsync    | time="2019-12-21T14:19:07Z" level=info msg="\n _______  _______  ______   _______           _        _______ \n(  ____ )(  ___  )(  __  \\ (  ____ \\|\\     /|( (    /|(  ____ \\\n| (    )|| (   ) || (  \\  )| (    \\/( \\   / )|  \\  ( || (    \\/\n| (____)|| |   | || |   ) || (_____  \\ (_) / |   \\ | || |      \n|  _____)| |   | || |   | |(_____  )  \\   /  | (\\ \\) || |      \n| (      | |   | || |   ) |      ) |   ) (   | | \\   || |      \n| )      | (___) || (__/  )/\\____) |   | |   | )  \\  || (____/\\\n|/       (_______)(______/ \\_______)   \\_/   |/    )_)(_______/\n"
podsync    | time="2019-12-21T14:19:07Z" level=info msg="running podsync" commit=fe02f8394aa0bb4ab9a46142113393759fd24324 date="2019-11-28T22:18:25Z" version=2.0.6
podsync    | time="2019-12-21T14:19:08Z" level=info msg="using youtube-dl 2019.11.05\n"
podsync    | time="2019-12-21T14:19:08Z" level=info msg="using ffmpeg ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers\nbuilt with gcc 8.3.0 (Alpine 8.3.0)\nconfiguration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --disable-debug\nlibavutil      56. 22.100 / 56. 22.100\nlibavcodec     58. 35.100 / 58. 35.100\nlibavformat    58. 20.100 / 58. 20.100\nlibavdevice    58.  5.100 / 58.  5.100\nlibavfilter     7. 40.101 /  7. 40.101\nlibavresample   4.  0.  0 /  4.  0.  0\nlibswscale      5.  3.100 /  5.  3.100\nlibswresample   3.  3.100 /  3.  3.100\nlibpostproc    55.  3.100 / 55.  3.100\n"
podsync    | time="2019-12-21T14:19:08Z" level=info msg="running listener at :8080"
podsync    | time="2019-12-21T14:19:08Z" level=info msg="-> updating https://www.youtube.com/channel/UCs6A_0Jm21SIvpdKyg9Gmxw/videos" feed_id=Pin64 format=video quality=high
podsync    | time="2019-12-21T14:19:08Z" level=info msg="! downloading episode https://youtube.com/watch?v=lwkcr3CvyCM" episode_id=lwkcr3CvyCM index=0
podsync    | time="2019-12-21T14:19:11Z" level=info msg="successfully updated feed in 3.733997845s, downloaded: 0 episode(s), next update at 2:24PM"

`

**Comment by mxpv** [comment]
Log says that it's downloading an episode and then states that 0 episodes downloaded. 
This happens when downloader got http error 429 from YouTube in response - too many requests. This means that YouTube temporary blocked your IP because you've sent too many queries.

From your configuration I see that you check for updates every 5 minutes - which is way too often. I suggest you to change the update period to something at least 1+ hours and wait about 6+ hours for YouTube to unblock your IP (it's not clear how many hours exactly you need to wait to get unbanned).

Also I've updated downloader code to log warning so it'll be more clear why there is 0 episodes downloaded during this update session.

**Comment by mxpv** [comment]
I'm going to close this, feel free to reopen if you have issues.
