### ISSUE TITLE
Question: Is it possible to get a podcast of all videos in "watch later" on YouTube (Podsync CLI)?

### ISSUE THREAD

**Issue by prokher** [mxpv/podsync#70]
I know FAQ states it is not possible. But FAQ tells about the podsync.net service. I am just curious, is it the same for the case when I use my our Youtube API token in Podsync CLI?

**Comment by bcongdon** [comment]
Unfortunately, its impossible to get your Watch Later playlist via the Youtube API (even if you're using your own API token) ([source](https://developers.google.com/youtube/v3/docs/playlistItems/list#errors_1))

Barring extraordinary measures (like manually scraping the Watch Later playlist page), I don't think this will be possible

**Comment by prokher** [comment]
@bcongdon, thank you for clarification, understood. Well, closing this cause there is nothing can be done.
