### ISSUE TITLE
Playlists cover art and channel name

### ISSUE THREAD

**Issue by mmarfil** [mxpv/podsync#71]
Is there any way to tell a playlist to use the channel cover art through the `config.toml`? As of now, playlist cover art are based on the latest episode thumbnail.

Somewhat related, is it possible to define a channel name through `config.toml` too? I tried an entry called `title` but it didn't work.

**Comment by AdamCurtisVT** [comment]
> In the config.toml file you can add the _cover_art_ attribute and specify a URL.
> 
> ```
> [feeds]
>   [feeds.ID1]
>   url = "{FEED_URL}" # URL address of a channel, group, user, or playlist. 
>   page_size = 50 # The number of episodes to query each update (keep in mind, that this might drain API token)
>   update_period = "12h" # How often query for updates, examples: "60m", "4h", "2h45m"
>   quality = "high" # or "low"
>   format = "video" # or "audio"
>   cover_art = "{image_url}"
> ```

**Comment by mmarfil** [comment]
Thank you very much @AdamCurtisVT 👍
