### ISSUE TITLE
Limit for maximum resolution of videos

### ISSUE THREAD

**Issue by Rpsl** [mxpv/podsync#74]
User Story: I want to download the video in good quality, but I don't want to download a few gigabytes of video because it is in 4k.

--

I think can add an optional item about maximum video quality (720p/1080p/1440p/2160p) to the config of feed and use it param for youtube-dl

https://github.com/mxpv/podsync/blob/master/pkg/ytdl/ytdl.go#L43

```
bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]
```

**Comment by mxpv** [comment]
Hello. Thanks for the feedback. Is this something that you want to control in a configuration file?

**Comment by Rpsl** [comment]
Yep. I think it maybe not requirement param of the feed in configuration file.

**Comment by SoftXperience** [comment]
Is this already included in release 2.0.7? It seems to not work on my machine. If I add max_height = 360 to my config, the video has still 1080p.
Also the readme shows max_height = "720", but as it is an Int, shouldn't it be max_height = 720?
