### ISSUE TITLE
I have no idea what I am doing....

### ISSUE THREAD

**Issue by TyroneTaylorPod** [mxpv/podsync#77]
I have been told by Max that this can be done with an exe. keep in mind I have no idea about coding but I did use the link to Amazon AWS and I added my youtube api and also the Vimeo api. I have tried to create stack 3x and each time it attempts to create stack and fails says ROLLBACK complete..not sure what I am doing wrong.

**Comment by TyroneTaylorPod** [comment]
Error message is this Parameter validation failed: parameter value for parameter name KeyName does not exist. Rollback requested by user.

**Comment by mxpv** [comment]
@TyroneTaylorPod If I get this right, you need to specify "SSH key name" properly in your CloudFormation template. Here is a tutorial how you can do it: https://docs.aws.amazon.com/ground-station/latest/ug/create-ec2-ssh-key-pair.html
Let me know if this helps.
