### ISSUE TITLE
Feed not appearing in pocketcast

### ISSUE THREAD

**Issue by streightedge** [mxpv/podsync#79]
Hi,

I have installed you're docker image to a server and it works fine but i can add the feed only to beyondpod app which is not my default podcast player. Pocketcast on the other hand can't find the feed (http://x.x.x.x:8080/ID1.xml).

Any ideas?

**Comment by Rpsl** [comment]
I use pocketcast and that work correct. 
Can you give additional information about your feed and error messages?

**Comment by streightedge** [comment]
I just get no results on pocketCast. Can I see  some logs somewere?
![image](https://user-images.githubusercontent.com/60396681/73367952-828a4b00-42b0-11ea-8546-904a3cd854aa.png)

**Comment by Rpsl** [comment]
```
192.168.x.x
```
It is your local ip, not available from internet. If you want use podsync with pocketcast, you need run that on server available from internet.

**Comment by streightedge** [comment]
Thats correct its on internal network. Didn't know that it has to be available from the internet. 

Thank you.

**Comment by mxpv** [comment]
there is no internet requirement, as long as your phone within the same network, it should work fine. However it won't work if you leave the network, use LTE, etc.

**Comment by streightedge** [comment]
Make sense :)  but it does not work apperenty. The phone is in the same 192.168....network but it cant find the rss feed (beyond pod can for exapmle)

**Comment by Rpsl** [comment]
It's can work with iTunes or somelike app who use parse xml native on device. For all I know pocketcast use his servers for manipulate with xml.

**Comment by streightedge** [comment]
ok but how does it work for @Rpsl than :D

**Comment by FrozenDragoon** [comment]
I can confirm that once the host is available on the internet, PocketCasts works great.  

Interestingly, downloads are done via direct connection to the server (rather than through PocketCasts servers). 
If you run a local DNS server (like PiHole), you can point your domain to the local server and downloads will occur over the local network (while at home) rather than over the internet.

**Comment by sqsuica** [comment]
I have the same issue. 
I can see the ID1.xml in my Synology folder /docker/PodSync/ID1.xml
The videos were downloaded onto /docker/PodSync/ID1
NOTE: Config is in /docker/PodSync

When I access the http://192.168.72.43:6969/ID1.xml on my Mac's browser or in PocketCast (iphone). It's showing no "This site can’t be reached". Should I at least be able to view the feed on my Mac? Any ideas?

Thanks

**Comment by sqsuica** [comment]
I figured out the issue and it's with my docker port setting not being configured correctly.

If you used Apple podcast app, the local feed will work fine.
