### ISSUE TITLE
Auto update? Or fresh container every time?

### ISSUE THREAD

**Issue by Rumik** [mxpv/podsync#82]
Hey there! I’m still new to images and containers and docker etc. Will my image and container auto update or do I need to manually get the latest image and install a new container each time there’s a new release?

Thanks!

**Comment by FrozenDragoon** [comment]
With docker you will need to manually grab the update and re-create your container. 

ex.
`docker pull mxpv/podsync:latest`
or if using compose:
`docker-compose pull && docker-compose up -d`

**Comment by mxpv** [comment]
@Rumik you can use `mxpv/podsync:latest` to pull latest available version or `mxpv/podsync:2.0` to get bug fixes like 2.0.X (as I plan to transition to 2.1 soon). Let me know if you need help.
