### ISSUE TITLE
failed to update feed, connection refused

### ISSUE THREAD

**Issue by Boycottangent** [mxpv/podsync#85]
Environment: CentOS 7, Use Docker Compose.
Run docker compose successfully but error logs shows:
```
podsync    | time="2020-02-04T12:12:24Z" 
level=error 
msg="failed to update feed: https://www.youtube.com/channel/UCI9DPD1b5_y7ApDJ00jdi5Q" 
error="failed to query channel: Get https://www.googleapis.com/youtube/v3/channels?alt=json&id=UCI9DPD1b5_y7ApDJ00jdi5Q&key=<...>&part=id%2Csnippet%2CcontentDetails: dial tcp: lookup www.googleapis.com on 127.0.0.11:53: read udp 127.0.0.1:52387->127.0.0.11:53: read: connection refused"
```
API Key is generated and used 
<img width="880" alt="图片" src="https://user-images.githubusercontent.com/23280916/73745074-21b9b180-478d-11ea-95eb-7973eb6bf438.png">

<img width="552" alt="图片" src="https://user-images.githubusercontent.com/23280916/73745236-82e18500-478d-11ea-8c9d-c506b60433a0.png">
  
What wrong 🤔

**Comment by Rpsl** [comment]
```
dial tcp: lookup www.googleapis.com on 127.0.0.11:53: read udp 127.0.0.1:52387->127.0.0.11:53: read: connection refused"
```
Some problem with dns in your setup. Error log says that can't resolve `www.googleapis.com` because local dns `127.0.0.11:53` not available

**Comment by Boycottangent** [comment]
Oops! forgot to open firewall port..

**Comment by weigeloveu** [comment]
> Oops! forgot to open firewall port..
I'm facing the same issues, how to open firewall port on android, any guide?
