### ISSUE TITLE
Error with Ubuntu server. No file is written in data folder

### ISSUE THREAD

**Issue by giagar5** [mxpv/podsync#86]
I'm using Ubuntu Server (raspberry like configuration). Ready to create a guide for this scenaario, however it doesn't work.

I could install docker, youtube, ffmpeg, then I downloaded, created config. But when I launch with config, nothing is written in the data folder (i created) and, I think as a consequence, the webpage cannot be accessed either.
There is no video nor audio files in the data folder, even if the log from the program seems fine and no error is produced.

Any idea on how to debug what is happening? I added the "debug = 1" parameter to docker but it doesn't produce any more info. What could be having problems to write?

The folder is in the home folder, so the access rights should be ok.

thanks

```
time="2020-02-06T20:03:36Z" level=info msg="\n _______  _______  ______   _______           _        _______ \n(  ____ )(  ___  )(  __  \\ (  ____ \\|\\     /|( (    /|(  ____ \\\n| (    )|| (   ) || (  \\  )| (    \\/( \\   / )|  \\  ( || (    \\/\n| (____)|| |   | || |   ) || (_____  \\ (_) / |   \\ | || |      \n|  _____)| |   | || |   | |(_____  )  \\   /  | (\\ \\) || |      \n| (      | |   | || |   ) |      ) |   ) (   | | \\   || |      \n| )      | (___) || (__/  )/\\____) |   | |   | )  \\  || (____/\\\n|/       (_______)(______/ \\_______)   \\_/   |/    )_)(_______/\n"
time="2020-02-06T20:03:36Z" level=info msg="running podsync" commit=9f4c926af1482fd1d22cc68275fee8b55548a775 date="2020-01-27T01:05:26Z" version=2.0.7
time="2020-02-06T20:03:42Z" level=info msg="using youtube-dl 2020.01.24\n"
time="2020-02-06T20:03:42Z" level=info msg="using ffmpeg ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers\nbuilt with gcc 8.3.0 (Alpine 8.3.0)\nconfiguration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --disable-debug\nlibavutil      56. 22.100 / 56. 22.100\nlibavcodec     58. 35.100 / 58. 35.100\nlibavformat    58. 20.100 / 58. 20.100\nlibavdevice    58.  5.100 / 58.  5.100\nlibavfilter     7. 40.101 /  7. 40.101\nlibavresample   4.  0.  0 /  4.  0.  0\nlibswscale      5.  3.100 /  5.  3.100\nlibswresample   3.  3.100 /  3.  3.100\nlibpostproc    55.  3.100 / 55.  3.100\n"
time="2020-02-06T20:03:42Z" level=info msg="-> updating https://www.youtube.com/channel/UClXK00XXDDKSJkjgqDqvDQ/featured" feed_id=AN format=audio quality=low
time="2020-02-06T20:03:42Z" level=info msg="running listener at :6969"
time="2020-02-06T20:03:43Z" level=info msg="! downloading episode
Created new playlist
```

**Comment by Rpsl** [comment]
Show your config and how you run podsync

**Comment by giagar5** [comment]
From your answer I understood that it was important how I launch podsync, so I used the official launching script and now the webserver is working. However the files are always not in the good directory:

/var/lib/docker/overlay2/f5a5f1597a9e8a06392d10f5cb9b3ae89345a57eee2704a207dc0510ab1b0925/merged/home/j5/podsync/data/

instead of simply

/home/j5/podsync/data

**Comment by Rpsl** [comment]
```
data_dir = "/home/j5/podsync/data"
```
When you work with docker, you use filesystem inside your docker container. Change it in config. Must be:
```
data_dir = "/app/data/"
```
because you mount this dir when run docker:
```
    -v $(pwd)/data:/app/data/ \
```

**Comment by giagar5** [comment]
now it works well... **thanks for the help.**

I didn't understand well why it works, expecially the change in the config file, however now it works beautifully..
