### ISSUE TITLE
audio can't load in podcast (Self hosted version)

### ISSUE THREAD

**Issue by Boycottangent** [mxpv/podsync#87]
Self host podsync in docker, I can subscribe podcast but can't play episodes. Cover and episode length are load correctly but audio seems failed to play.

feed address is http://167.179.74.29:8081/ID1.xml Can someone test this feed?

audio file is indeed downloaded and saved, I can access mp3 file in serve. 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/23280916/74077519-46e34400-4a5b-11ea-8c73-18c75b585114.png">

In my case, the xml file use `localhost` to direct the url of audio file, I wonder if this cause the problem.
```yaml
<pubDate>Wed, 05 Feb 2020 13:00:11 +0000</pubDate>
<enclosure url="http://localhost:8081/ID1/WvVnuPEkqu4.mp3" length="10328277" type="audio/mpeg"/>
```

**Comment by Rpsl** [comment]
You can use settings `hostname` in your config.toml. See details in [README.md](https://github.com/mxpv/podsync/blob/master/README.md)

```
[server]
port = 8080
hostname = "https://my.test.host:4443"
```

**Comment by Boycottangent** [comment]
There's something that I am confused. The port  used in `hostname` field (like 4443) should be different from the serve port (like 8080)? I used the same port but got `connection refused` problem

**Comment by Rpsl** [comment]
It's depend on your configuration. Basically they must be the same.

Try for your configuration this settings:

```
[server]
port = 8081
hostname = "http://167.179.74.29:8081"
```

**Comment by Boycottangent** [comment]
Works! Thanks!

**Comment by wongtttads** [comment]
thanks, it works.
