### ISSUE TITLE
Is there a guide or a how-to?!

### ISSUE THREAD

**Issue by JanusGH** [mxpv/podsync#93]
Hello, I would like to know if there is a guide somewhere that explains how this whole system is supposed to work? (A guide that can be understood/followed by regular users, not just programmers.)
I just want to be able to play a select few YT cannels/playlists (audio only) on my phone/tablet with my podcast app (podcast addict).
What do I need to do to make that happen? Thanks.

**Comment by mxpv** [comment]
Hello. Have you checked this readme? https://github.com/mxpv/podsync/blob/master/README.md
There is a configuration example and how to run it.
Also there are a few docs here: https://github.com/mxpv/podsync/tree/master/docs

**Comment by ajjp5o7** [comment]
I also would appreciate a guide.
The readme you provided is too complicated for a regular user to understand. 
A video tutorial would be most helpful.

**Comment by JanusGH** [comment]
Yes, that was the point of my inquiry. I did see those files... the readme and the docs, but as was already pointed out those are not really suitable for 'regular' users with little/no experience with (basic) programing, coding or just the inner workings of Linux/Android. Most people just don't know that stuff.
Which is why it would be VERY much appreciated if you (or someone!) could put together a simple step-by-step guide or video how we can use podsync on our phones/tablets (usually Android ...maybe also iOS?) and possibly even our computers (Windows/Mac/Linux would be the main ones I guess). But obviously primarily for Android... That's what most people are using today for podcasts and such.
It would be great if you could help us all out here. Thank you.

P.S.: It is very regrettable that your website podsync.net is not functional anymore. That was and probably would still be the most userfriendly method.

**Comment by Phantop** [comment]
Actually, speaking of the website, it would be neat if we could just self host copies of it to make it easier.

**Comment by Rumik** [comment]
Hosting a local version of the site would certainly ale managing our podcast feeds easier!
