### ISSUE TITLE
Run it in Android - Termux

### ISSUE THREAD

**Issue by maguecbr** [mxpv/podsync#97]
Hi everyone,

Does someone podsync CLI run in Android? I could run in a rooted phone, but only in rooted mode (and this way I cant use youtube-dl and ffmpeg).

In user mode I cant run binaries.

Any solution?

Thank you all!

**Comment by mxpv** [comment]
Hey. Can you describe your use case? CLI expected to be running on a server.

**Comment by maguecbr** [comment]
> Hey. Can you describe your use case? CLI is expected to be running on a server.

Sure. Android is linux-based, so I download an app that brings a terminal to android (termux). 

Then, I installed python and, using the command "pip", I installed both ffmpeg and youtube-dl in android.

The next step was run podsync, and at this point the problems began. It is impossible to run binaries in partitions mounted as "NOEXEC", as all user-level accessible directories that I found are mounted this way, by security reasons.

I tried run podsync as superuser in a folder not mounted as "NOEXEC" (I created /dev/podsync). I was able to run the podsync binary, but it failed to run youtube-dl and ffmpeg.

And that's where I'm stuck.

**Comment by maguecbr** [comment]
My reason to run podsync in Android is to make a local server for podcasts extracted from youtube.
With the xml generated, I may be able to easily access subscribe the podcast with a podcast application installed in the same device.
This way I wouldn't need an external server running it.

**Comment by mxpv** [comment]
There are binaries for Linux available in Releases. Have you tried those?

**Comment by weigeloveu** [comment]
> There are binaries for Linux available in Releases. Have you tried those?

I tried on termux arm 64, got connection refused

**Comment by mxpv** [comment]
I'm going to close this, feel free to reopen if you still have questions.
