### ISSUE TITLE
failed to load config file

### ISSUE THREAD

**Issue by poisonoff** [mxpv/podsync#98]
where should I put the config file？
I  run it via docker,but always warns me about
**_level=fatal msg="failed to load configuration file" error="failed to load config file: read config.toml: is a directory"_**

thank you so much.

**Comment by mxpv** [comment]
Could you please provide how do you run container?

**Comment by poisonoff** [comment]
> Could you please provide how do you run container?

Well, I'm so sorry about that I have no experience with programing , I just followed the steps in your _README_ file :Made a _config.toml_ file with text editor ,then googled to install DOCKER,and ran the  Commands below in _iterm_:
_$ docker pull mxpv/podsync:latest
$ docker run \
    -p 8080:8080 \
    -v $(pwd)/data:/app/data/ \
    -v $(pwd)/config.toml:/app/config.toml \
    mxpv/podsync:latest_

And then it warns that:
_FATA[2020-03-10T14:07:22+08:00] failed to load configuration file             
error="failed to load config file: read config.toml: is a directory"_

It is **quite difficult** for me to find out what's wrong with this...
Could you please give me a hand?
**THANK YOU SO MUCH!**

**Comment by WillYouth** [comment]
Hi, any updates on this? I faced the same problem. Running on Windows too. Run using docker

**Comment by WillYouth** [comment]
@poisonoff Found this: https://github.com/mxpv/podsync/issues/201#issuecomment-812907121
