### ISSUE TITLE
All Updates getting error "Project 664322059124 has been scheduled for deletion"

### ISSUE THREAD

**Issue by tuxpeople** [mxpv/podsync#99]
For a while now (but I just discovered it now), my feeds (regardless if channels or playlists) are not updating and all of the are generating this error:

`podsync_1           | time="2020-03-12T09:20:04Z" level=error msg="failed to update feed: https://www.youtube.com/channel/UCjjwExYSPRWwjj9WwydrVmA" error="failed to query channel: googleapi: Error 403: Project 664322059124 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project., accessNotConfigured"`

I'm not aware of any changes from my side...

**Comment by mxpv** [comment]
Something wrong with your YouTube API Key. Try making another one.

**Comment by tuxpeople** [comment]
My apology. I created the API Key in a test project, which I recently deleted. I now created a new one, specifically for the podsync API key.
